#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain

#include "Basic.hpp"

#include "Ability_activation_logic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain.AIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C
// 0x0000 (0x0040 - 0x0040)
class UAIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C final : public UPyAIAbilityActivation_ChangeButtonIfNoBuff
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C">();
	}
	static class UAIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C>();
	}
};
static_assert(alignof(UAIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C) == 0x000008, "Wrong alignment on UAIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C");
static_assert(sizeof(UAIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C) == 0x000040, "Wrong size on UAIAbilityActivivation_ChangeButtonIfNoFriendshipBuff_Captain_C");

}

