#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BuffAbility_10534401_BP

#include "Basic.hpp"

#include "PyAbility_105344_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BuffAbility_10534401_BP.BuffAbility_10534401_BP_C
// 0x0008 (0x1420 - 0x1418)
class UBuffAbility_10534401_BP_C final : public UPyBuffAbility_10534401
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1418(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BuffAbility_10534401_BP(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void ReceiveTick(float DeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BuffAbility_10534401_BP_C">();
	}
	static class UBuffAbility_10534401_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10534401_BP_C>();
	}
};
static_assert(alignof(UBuffAbility_10534401_BP_C) == 0x000008, "Wrong alignment on UBuffAbility_10534401_BP_C");
static_assert(sizeof(UBuffAbility_10534401_BP_C) == 0x001420, "Wrong size on UBuffAbility_10534401_BP_C");
static_assert(offsetof(UBuffAbility_10534401_BP_C, UberGraphFrame) == 0x001418, "Member 'UBuffAbility_10534401_BP_C::UberGraphFrame' has a wrong offset!");

}

