#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClientGCActorManager

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ClientGCActorManager.ClientGCActorManager_C
// 0x0010 (0x0770 - 0x0760)
class AClientGCActorManager_C final : public AChaosClientGCManagerActor
{
public:
	class UArrowComponent*                        Arrow;                                             // 0x0760(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ClientGCActorManager_C">();
	}
	static class AClientGCActorManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AClientGCActorManager_C>();
	}
};
static_assert(alignof(AClientGCActorManager_C) == 0x000010, "Wrong alignment on AClientGCActorManager_C");
static_assert(sizeof(AClientGCActorManager_C) == 0x000770, "Wrong size on AClientGCActorManager_C");
static_assert(offsetof(AClientGCActorManager_C, Arrow) == 0x000760, "Member 'AClientGCActorManager_C::Arrow' has a wrong offset!");
static_assert(offsetof(AClientGCActorManager_C, DefaultSceneRoot) == 0x000768, "Member 'AClientGCActorManager_C::DefaultSceneRoot' has a wrong offset!");

}

