#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cue_Scope_Loop_10319302_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cue_Scope_Loop_10319302_BP.Cue_Scope_Loop_10319302_BP_C
// 0x0008 (0x0F38 - 0x0F30)
class ACue_Scope_Loop_10319302_BP_C final : public AMarvelCueNotify_Scope
{
public:
	class UNiagaraComponent*                      Niagara;                                           // 0x0F30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cue_Scope_Loop_10319302_BP_C">();
	}
	static class ACue_Scope_Loop_10319302_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Scope_Loop_10319302_BP_C>();
	}
};
static_assert(alignof(ACue_Scope_Loop_10319302_BP_C) == 0x000008, "Wrong alignment on ACue_Scope_Loop_10319302_BP_C");
static_assert(sizeof(ACue_Scope_Loop_10319302_BP_C) == 0x000F38, "Wrong size on ACue_Scope_Loop_10319302_BP_C");
static_assert(offsetof(ACue_Scope_Loop_10319302_BP_C, Niagara) == 0x000F30, "Member 'ACue_Scope_Loop_10319302_BP_C::Niagara' has a wrong offset!");

}

