#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EffectiveComponent_10427501_BP

#include "Basic.hpp"

#include "Hero_1042_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EffectiveComponent_10427501_BP.EffectiveComponent_10427501_BP_C
// 0x0000 (0x1C10 - 0x1C10)
class UEffectiveComponent_10427501_BP_C final : public UEffectiveComponent_10427501
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EffectiveComponent_10427501_BP_C">();
	}
	static class UEffectiveComponent_10427501_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffectiveComponent_10427501_BP_C>();
	}
};
static_assert(alignof(UEffectiveComponent_10427501_BP_C) == 0x000010, "Wrong alignment on UEffectiveComponent_10427501_BP_C");
static_assert(sizeof(UEffectiveComponent_10427501_BP_C) == 0x001C10, "Wrong size on UEffectiveComponent_10427501_BP_C");

}

