#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hulk_TheThing_AIGuidePoint

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hulk_TheThing_AIGuidePoint.Hulk_TheThing_AIGuidePoint_C
// 0x0008 (0x0600 - 0x05F8)
class AHulk_TheThing_AIGuidePoint_C final : public AActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x05F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Hulk_TheThing_AIGuidePoint_C">();
	}
	static class AHulk_TheThing_AIGuidePoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHulk_TheThing_AIGuidePoint_C>();
	}
};
static_assert(alignof(AHulk_TheThing_AIGuidePoint_C) == 0x000008, "Wrong alignment on AHulk_TheThing_AIGuidePoint_C");
static_assert(sizeof(AHulk_TheThing_AIGuidePoint_C) == 0x000600, "Wrong size on AHulk_TheThing_AIGuidePoint_C");
static_assert(offsetof(AHulk_TheThing_AIGuidePoint_C, DefaultSceneRoot) == 0x0005F8, "Member 'AHulk_TheThing_AIGuidePoint_C::DefaultSceneRoot' has a wrong offset!");

}

