#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IndicatorExtensiomRowInfo

#include "Basic.hpp"

#include "IndicatorExtensionModeInfo_structs.hpp"


namespace SDK
{

// UserDefinedStruct IndicatorExtensiomRowInfo.IndicatorExtensiomRowInfo
// 0x0058 (0x0058 - 0x0000)
struct FIndicatorExtensiomRowInfo final
{
public:
	bool                                          Delivery_49_64E9A8AB4A28078BF6E2109DEF098088;      // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BaseComment_53_EB3E87C04E8175659D07DB97294125CE;   // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   IndicatorClass_46_80D816354E9745DC13349EA3F4AE9130; // 0x0018(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FIndicatorExtensionModeInfo>    ModeConfigs_45_2C0054B54AA3DE4EE20EC89CD453A8C4;   // 0x0048(0x0010)(Edit, BlueprintVisible)
};
static_assert(alignof(FIndicatorExtensiomRowInfo) == 0x000008, "Wrong alignment on FIndicatorExtensiomRowInfo");
static_assert(sizeof(FIndicatorExtensiomRowInfo) == 0x000058, "Wrong size on FIndicatorExtensiomRowInfo");
static_assert(offsetof(FIndicatorExtensiomRowInfo, Delivery_49_64E9A8AB4A28078BF6E2109DEF098088) == 0x000000, "Member 'FIndicatorExtensiomRowInfo::Delivery_49_64E9A8AB4A28078BF6E2109DEF098088' has a wrong offset!");
static_assert(offsetof(FIndicatorExtensiomRowInfo, BaseComment_53_EB3E87C04E8175659D07DB97294125CE) == 0x000008, "Member 'FIndicatorExtensiomRowInfo::BaseComment_53_EB3E87C04E8175659D07DB97294125CE' has a wrong offset!");
static_assert(offsetof(FIndicatorExtensiomRowInfo, IndicatorClass_46_80D816354E9745DC13349EA3F4AE9130) == 0x000018, "Member 'FIndicatorExtensiomRowInfo::IndicatorClass_46_80D816354E9745DC13349EA3F4AE9130' has a wrong offset!");
static_assert(offsetof(FIndicatorExtensiomRowInfo, ModeConfigs_45_2C0054B54AA3DE4EE20EC89CD453A8C4) == 0x000048, "Member 'FIndicatorExtensiomRowInfo::ModeConfigs_45_2C0054B54AA3DE4EE20EC89CD453A8C4' has a wrong offset!");

}

