#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KnockUp_101741_Explode

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_101741_Explode.KnockUp_101741_Explode_C
// 0x0000 (0x20A0 - 0x20A0)
class UKnockUp_101741_Explode_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_101741_Explode_C">();
	}
	static class UKnockUp_101741_Explode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_101741_Explode_C>();
	}
};
static_assert(alignof(UKnockUp_101741_Explode_C) == 0x000008, "Wrong alignment on UKnockUp_101741_Explode_C");
static_assert(sizeof(UKnockUp_101741_Explode_C) == 0x0020A0, "Wrong size on UKnockUp_101741_Explode_C");

}

