#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: One032_CharacterBP

#include "Basic.hpp"

#include "PySquirrelGirlCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 1032_CharacterBP.1032_CharacterBP_C
// 0x0010 (0x1BF0 - 0x1BE0)
class AOne032_CharacterBP_C final : public APySquirrelGirlCharacter
{
public:
	class UPhysicalInteractionComponent*          PhysicalInteraction;                               // 0x1BE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1032_CharacterBP_C">();
	}
	static class AOne032_CharacterBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOne032_CharacterBP_C>();
	}
};
static_assert(alignof(AOne032_CharacterBP_C) == 0x000010, "Wrong alignment on AOne032_CharacterBP_C");
static_assert(sizeof(AOne032_CharacterBP_C) == 0x001BF0, "Wrong size on AOne032_CharacterBP_C");
static_assert(offsetof(AOne032_CharacterBP_C, PhysicalInteraction) == 0x001BE0, "Member 'AOne032_CharacterBP_C::PhysicalInteraction' has a wrong offset!");

}

