#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: One051_CharacterBP

#include "Basic.hpp"

#include "Hero_1051_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 1051_CharacterBP.1051_CharacterBP_C
// 0x0000 (0x1C00 - 0x1C00)
class AOne051_CharacterBP_C final : public ABenjaminGrimCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1051_CharacterBP_C">();
	}
	static class AOne051_CharacterBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOne051_CharacterBP_C>();
	}
};
static_assert(alignof(AOne051_CharacterBP_C) == 0x000010, "Wrong alignment on AOne051_CharacterBP_C");
static_assert(sizeof(AOne051_CharacterBP_C) == 0x001C00, "Wrong size on AOne051_CharacterBP_C");

}

