#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_10303101_BP

#include "Basic.hpp"

#include "Hero_1030_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_10303101_BP.Projectile_10303101_BP_C
// 0x0000 (0x44D0 - 0x44D0)
class AProjectile_10303101_BP_C final : public AProjectile_10303101
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Projectile_10303101_BP_C">();
	}
	static class AProjectile_10303101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10303101_BP_C>();
	}
};
static_assert(alignof(AProjectile_10303101_BP_C) == 0x000010, "Wrong alignment on AProjectile_10303101_BP_C");
static_assert(sizeof(AProjectile_10303101_BP_C) == 0x0044D0, "Wrong size on AProjectile_10303101_BP_C");

}

