#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Py3DUI_CommonItem

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass Py3DUI_CommonItem.Py3DUI_CommonItem
// 0x0080 (0x0678 - 0x05F8)
class APy3DUI_CommonItem final : public AActor
{
public:
	float                                         MaximumRotationAngle;                              // 0x05F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RotationInterpSpeed;                               // 0x05FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxAnglePerSecond;                                 // 0x0600(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ActorRotationSpeed;                                // 0x0604(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            Curve_InterpSpeed;                                 // 0x0608(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SprayAnimTime;                                     // 0x0610(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MouseSensitivity;                                  // 0x0614(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_ShowSpray;                                 // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<EItemType, TSubclassOf<class AActor>>    ItemLightBP;                                       // 0x0620(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	float                                         ManualFocusDistance;                               // 0x0670(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Py3DUI_CommonItem">();
	}
	static class APy3DUI_CommonItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<APy3DUI_CommonItem>();
	}
};
static_assert(alignof(APy3DUI_CommonItem) == 0x000008, "Wrong alignment on APy3DUI_CommonItem");
static_assert(sizeof(APy3DUI_CommonItem) == 0x000678, "Wrong size on APy3DUI_CommonItem");
static_assert(offsetof(APy3DUI_CommonItem, MaximumRotationAngle) == 0x0005F8, "Member 'APy3DUI_CommonItem::MaximumRotationAngle' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, RotationInterpSpeed) == 0x0005FC, "Member 'APy3DUI_CommonItem::RotationInterpSpeed' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, MaxAnglePerSecond) == 0x000600, "Member 'APy3DUI_CommonItem::MaxAnglePerSecond' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, ActorRotationSpeed) == 0x000604, "Member 'APy3DUI_CommonItem::ActorRotationSpeed' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, Curve_InterpSpeed) == 0x000608, "Member 'APy3DUI_CommonItem::Curve_InterpSpeed' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, SprayAnimTime) == 0x000610, "Member 'APy3DUI_CommonItem::SprayAnimTime' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, MouseSensitivity) == 0x000614, "Member 'APy3DUI_CommonItem::MouseSensitivity' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, AkEvent_ShowSpray) == 0x000618, "Member 'APy3DUI_CommonItem::AkEvent_ShowSpray' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, ItemLightBP) == 0x000620, "Member 'APy3DUI_CommonItem::ItemLightBP' has a wrong offset!");
static_assert(offsetof(APy3DUI_CommonItem, ManualFocusDistance) == 0x000670, "Member 'APy3DUI_CommonItem::ManualFocusDistance' has a wrong offset!");

}

