#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103421

#include "Basic.hpp"

#include "Hero_1034_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103421.PyCue_Ability_Loop_10342101
// 0x0010 (0x23F0 - 0x23E0)
class APyCue_Ability_Loop_10342101 final : public ACue_Ability_Loop_10342101
{
public:
	class UFXSystemAsset*                         CustomRemoveFX;                                    // 0x23E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnExecuteFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Loop_10342101">();
	}
	static class APyCue_Ability_Loop_10342101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Ability_Loop_10342101>();
	}
};
static_assert(alignof(APyCue_Ability_Loop_10342101) == 0x000010, "Wrong alignment on APyCue_Ability_Loop_10342101");
static_assert(sizeof(APyCue_Ability_Loop_10342101) == 0x0023F0, "Wrong size on APyCue_Ability_Loop_10342101");
static_assert(offsetof(APyCue_Ability_Loop_10342101, CustomRemoveFX) == 0x0023E0, "Member 'APyCue_Ability_Loop_10342101::CustomRemoveFX' has a wrong offset!");

}

