#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102332

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_102332.PyAbility_102332
// 0x0000 (0x2DF0 - 0x2DF0)
class UPyAbility_102332 : public UMarvelAeroBaseAbility
{
public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_102332">();
	}
	static class UPyAbility_102332* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102332>();
	}
};
static_assert(alignof(UPyAbility_102332) == 0x000008, "Wrong alignment on UPyAbility_102332");
static_assert(sizeof(UPyAbility_102332) == 0x002DF0, "Wrong size on UPyAbility_102332");

// PythonClass PyAbility_102332.PyConfig_102332
// 0x0000 (0x00F8 - 0x00F8)
class UPyConfig_102332 final : public UConfig_AeroBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_102332">();
	}
	static class UPyConfig_102332* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_102332>();
	}
};
static_assert(alignof(UPyConfig_102332) == 0x000008, "Wrong alignment on UPyConfig_102332");
static_assert(sizeof(UPyConfig_102332) == 0x0000F8, "Wrong size on UPyConfig_102332");

}

