#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103511

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_103511.PyCue_Scope_HitImpact_10351101.OnExecuteAudio
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Scope_HitImpact_10351101_OnExecuteAudio final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Scope_HitImpact_10351101_OnExecuteAudio) == 0x000008, "Wrong alignment on PyCue_Scope_HitImpact_10351101_OnExecuteAudio");
static_assert(sizeof(PyCue_Scope_HitImpact_10351101_OnExecuteAudio) == 0x0001C0, "Wrong size on PyCue_Scope_HitImpact_10351101_OnExecuteAudio");
static_assert(offsetof(PyCue_Scope_HitImpact_10351101_OnExecuteAudio, MyTarget) == 0x000000, "Member 'PyCue_Scope_HitImpact_10351101_OnExecuteAudio::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Scope_HitImpact_10351101_OnExecuteAudio, Parameters) == 0x000008, "Member 'PyCue_Scope_HitImpact_10351101_OnExecuteAudio::Parameters' has a wrong offset!");

}

