#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102411

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_102411.PyCue_Scope_Loop_10241101.WhileActive
// 0x01C8 (0x01C8 - 0x0000)
struct PyCue_Scope_Loop_10241101_WhileActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
	bool                                          ReturnValue;                                       // 0x01C0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyCue_Scope_Loop_10241101_WhileActive) == 0x000008, "Wrong alignment on PyCue_Scope_Loop_10241101_WhileActive");
static_assert(sizeof(PyCue_Scope_Loop_10241101_WhileActive) == 0x0001C8, "Wrong size on PyCue_Scope_Loop_10241101_WhileActive");
static_assert(offsetof(PyCue_Scope_Loop_10241101_WhileActive, MyTarget) == 0x000000, "Member 'PyCue_Scope_Loop_10241101_WhileActive::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Scope_Loop_10241101_WhileActive, Parameters) == 0x000008, "Member 'PyCue_Scope_Loop_10241101_WhileActive::Parameters' has a wrong offset!");
static_assert(offsetof(PyCue_Scope_Loop_10241101_WhileActive, ReturnValue) == 0x0001C0, "Member 'PyCue_Scope_Loop_10241101_WhileActive::ReturnValue' has a wrong offset!");

}

