#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_213

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_213.PyMarvelCueNotify_Quip.OnExecute
// 0x01C8 (0x01C8 - 0x0000)
struct PyMarvelCueNotify_Quip_OnExecute final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
	bool                                          ReturnValue;                                       // 0x01C0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyMarvelCueNotify_Quip_OnExecute) == 0x000008, "Wrong alignment on PyMarvelCueNotify_Quip_OnExecute");
static_assert(sizeof(PyMarvelCueNotify_Quip_OnExecute) == 0x0001C8, "Wrong size on PyMarvelCueNotify_Quip_OnExecute");
static_assert(offsetof(PyMarvelCueNotify_Quip_OnExecute, MyTarget) == 0x000000, "Member 'PyMarvelCueNotify_Quip_OnExecute::MyTarget' has a wrong offset!");
static_assert(offsetof(PyMarvelCueNotify_Quip_OnExecute, Parameters) == 0x000008, "Member 'PyMarvelCueNotify_Quip_OnExecute::Parameters' has a wrong offset!");
static_assert(offsetof(PyMarvelCueNotify_Quip_OnExecute, ReturnValue) == 0x0001C0, "Member 'PyMarvelCueNotify_Quip_OnExecute::ReturnValue' has a wrong offset!");

}

