#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104558

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_104558.PyConfig_104558
// 0x1098 (0x1130 - 0x0098)
class UPyConfig_104558 final : public UMarvelAbilityConfig
{
public:
	float                                         MaxShootAngle;                                     // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMarvelAbilityTraceContext             EnemyTraceContext;                                 // 0x00A0(0x1080)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGameplayTag                           BerserkTag;                                        // 0x1120(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_104558">();
	}
	static class UPyConfig_104558* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_104558>();
	}
};
static_assert(alignof(UPyConfig_104558) == 0x000010, "Wrong alignment on UPyConfig_104558");
static_assert(sizeof(UPyConfig_104558) == 0x001130, "Wrong size on UPyConfig_104558");
static_assert(offsetof(UPyConfig_104558, MaxShootAngle) == 0x000098, "Member 'UPyConfig_104558::MaxShootAngle' has a wrong offset!");
static_assert(offsetof(UPyConfig_104558, EnemyTraceContext) == 0x0000A0, "Member 'UPyConfig_104558::EnemyTraceContext' has a wrong offset!");
static_assert(offsetof(UPyConfig_104558, BerserkTag) == 0x001120, "Member 'UPyConfig_104558::BerserkTag' has a wrong offset!");

// PythonClass PyAbility_104558.PyAbility_104558
// 0x0000 (0x2A40 - 0x2A40)
class UPyAbility_104558 : public UAbility_108
{
public:
	void BeginPlay();
	void EndPlay();
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnBerserkTagUpdate(const struct FGameplayTag& TagUpdated, bool TagExists);
	void NativeOnMontageEvent(const class FString& EventTag);
	bool CanActivate();
	void NativeOnMontageCompleted(const class FString& EventTag);
	void OnTraceResults(class AActor* ScopeActor, const TArray<struct FHitResult>& HitResults);
	void OnTargetDeath(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameter);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_104558">();
	}
	static class UPyAbility_104558* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104558>();
	}
};
static_assert(alignof(UPyAbility_104558) == 0x000008, "Wrong alignment on UPyAbility_104558");
static_assert(sizeof(UPyAbility_104558) == 0x002A40, "Wrong size on UPyAbility_104558");

}

