#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_105344

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_105344.PyBuffAbility_10534401.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyBuffAbility_10534401_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_10534401_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyBuffAbility_10534401_K2_OnEndAbility");
static_assert(sizeof(PyBuffAbility_10534401_K2_OnEndAbility) == 0x000001, "Wrong size on PyBuffAbility_10534401_K2_OnEndAbility");
static_assert(offsetof(PyBuffAbility_10534401_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyBuffAbility_10534401_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// PythonFunction PyAbility_105344.PyBuffAbility_10534401.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct PyBuffAbility_10534401_ReceiveTick final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_10534401_ReceiveTick) == 0x000004, "Wrong alignment on PyBuffAbility_10534401_ReceiveTick");
static_assert(sizeof(PyBuffAbility_10534401_ReceiveTick) == 0x000004, "Wrong size on PyBuffAbility_10534401_ReceiveTick");
static_assert(offsetof(PyBuffAbility_10534401_ReceiveTick, DeltaTime) == 0x000000, "Member 'PyBuffAbility_10534401_ReceiveTick::DeltaTime' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_105344_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_CanActivate) == 0x000001, "Wrong alignment on PyAbility_105344_CanActivate");
static_assert(sizeof(PyAbility_105344_CanActivate) == 0x000001, "Wrong size on PyAbility_105344_CanActivate");
static_assert(offsetof(PyAbility_105344_CanActivate, ReturnValue) == 0x000000, "Member 'PyAbility_105344_CanActivate::ReturnValue' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_105344_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyAbility_105344_K2_OnEndAbility");
static_assert(sizeof(PyAbility_105344_K2_OnEndAbility) == 0x000001, "Wrong size on PyAbility_105344_K2_OnEndAbility");
static_assert(offsetof(PyAbility_105344_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyAbility_105344_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.NativeOnMontageCompleted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_105344_NativeOnMontageCompleted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_NativeOnMontageCompleted) == 0x000008, "Wrong alignment on PyAbility_105344_NativeOnMontageCompleted");
static_assert(sizeof(PyAbility_105344_NativeOnMontageCompleted) == 0x000010, "Wrong size on PyAbility_105344_NativeOnMontageCompleted");
static_assert(offsetof(PyAbility_105344_NativeOnMontageCompleted, Tag) == 0x000000, "Member 'PyAbility_105344_NativeOnMontageCompleted::Tag' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.NativeOnMontageInterrupted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_105344_NativeOnMontageInterrupted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_NativeOnMontageInterrupted) == 0x000008, "Wrong alignment on PyAbility_105344_NativeOnMontageInterrupted");
static_assert(sizeof(PyAbility_105344_NativeOnMontageInterrupted) == 0x000010, "Wrong size on PyAbility_105344_NativeOnMontageInterrupted");
static_assert(offsetof(PyAbility_105344_NativeOnMontageInterrupted, Tag) == 0x000000, "Member 'PyAbility_105344_NativeOnMontageInterrupted::Tag' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.NativeOnMontageCancelled
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_105344_NativeOnMontageCancelled final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_NativeOnMontageCancelled) == 0x000008, "Wrong alignment on PyAbility_105344_NativeOnMontageCancelled");
static_assert(sizeof(PyAbility_105344_NativeOnMontageCancelled) == 0x000010, "Wrong size on PyAbility_105344_NativeOnMontageCancelled");
static_assert(offsetof(PyAbility_105344_NativeOnMontageCancelled, Tag) == 0x000000, "Member 'PyAbility_105344_NativeOnMontageCancelled::Tag' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.NativeOnMontageEvent
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_105344_NativeOnMontageEvent final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_NativeOnMontageEvent) == 0x000008, "Wrong alignment on PyAbility_105344_NativeOnMontageEvent");
static_assert(sizeof(PyAbility_105344_NativeOnMontageEvent) == 0x000010, "Wrong size on PyAbility_105344_NativeOnMontageEvent");
static_assert(offsetof(PyAbility_105344_NativeOnMontageEvent, Tag) == 0x000000, "Member 'PyAbility_105344_NativeOnMontageEvent::Tag' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct PyAbility_105344_ReceiveTick final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_ReceiveTick) == 0x000004, "Wrong alignment on PyAbility_105344_ReceiveTick");
static_assert(sizeof(PyAbility_105344_ReceiveTick) == 0x000004, "Wrong size on PyAbility_105344_ReceiveTick");
static_assert(offsetof(PyAbility_105344_ReceiveTick, DeltaTime) == 0x000000, "Member 'PyAbility_105344_ReceiveTick::DeltaTime' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.GetMontagePosition
// 0x0004 (0x0004 - 0x0000)
struct PyAbility_105344_GetMontagePosition final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_GetMontagePosition) == 0x000004, "Wrong alignment on PyAbility_105344_GetMontagePosition");
static_assert(sizeof(PyAbility_105344_GetMontagePosition) == 0x000004, "Wrong size on PyAbility_105344_GetMontagePosition");
static_assert(offsetof(PyAbility_105344_GetMontagePosition, ReturnValue) == 0x000000, "Member 'PyAbility_105344_GetMontagePosition::ReturnValue' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.PyCallServerOnHit
// 0x0070 (0x0070 - 0x0000)
struct PyAbility_105344_PyCallServerOnHit final
{
public:
	class APawn*                                  Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Transform;                                         // 0x0010(0x0060)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_PyCallServerOnHit) == 0x000010, "Wrong alignment on PyAbility_105344_PyCallServerOnHit");
static_assert(sizeof(PyAbility_105344_PyCallServerOnHit) == 0x000070, "Wrong size on PyAbility_105344_PyCallServerOnHit");
static_assert(offsetof(PyAbility_105344_PyCallServerOnHit, Actor) == 0x000000, "Member 'PyAbility_105344_PyCallServerOnHit::Actor' has a wrong offset!");
static_assert(offsetof(PyAbility_105344_PyCallServerOnHit, Transform) == 0x000010, "Member 'PyAbility_105344_PyCallServerOnHit::Transform' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.MulticastOnHit
// 0x0070 (0x0070 - 0x0000)
struct PyAbility_105344_MulticastOnHit final
{
public:
	class APawn*                                  Hit_actor;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Transform;                                         // 0x0010(0x0060)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_MulticastOnHit) == 0x000010, "Wrong alignment on PyAbility_105344_MulticastOnHit");
static_assert(sizeof(PyAbility_105344_MulticastOnHit) == 0x000070, "Wrong size on PyAbility_105344_MulticastOnHit");
static_assert(offsetof(PyAbility_105344_MulticastOnHit, Hit_actor) == 0x000000, "Member 'PyAbility_105344_MulticastOnHit::Hit_actor' has a wrong offset!");
static_assert(offsetof(PyAbility_105344_MulticastOnHit, Transform) == 0x000010, "Member 'PyAbility_105344_MulticastOnHit::Transform' has a wrong offset!");

// PythonFunction PyAbility_105344.PyAbility_105344.Py_OnHit_Dispatch
// 0x0070 (0x0070 - 0x0000)
struct PyAbility_105344_Py_OnHit_Dispatch final
{
public:
	class APawn*                                  Hit_actor;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Transform;                                         // 0x0010(0x0060)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_105344_Py_OnHit_Dispatch) == 0x000010, "Wrong alignment on PyAbility_105344_Py_OnHit_Dispatch");
static_assert(sizeof(PyAbility_105344_Py_OnHit_Dispatch) == 0x000070, "Wrong size on PyAbility_105344_Py_OnHit_Dispatch");
static_assert(offsetof(PyAbility_105344_Py_OnHit_Dispatch, Hit_actor) == 0x000000, "Member 'PyAbility_105344_Py_OnHit_Dispatch::Hit_actor' has a wrong offset!");
static_assert(offsetof(PyAbility_105344_Py_OnHit_Dispatch, Transform) == 0x000010, "Member 'PyAbility_105344_Py_OnHit_Dispatch::Transform' has a wrong offset!");

// PythonFunction PyAbility_105344.PyBuffAbility_10534402.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyBuffAbility_10534402_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_10534402_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyBuffAbility_10534402_K2_OnEndAbility");
static_assert(sizeof(PyBuffAbility_10534402_K2_OnEndAbility) == 0x000001, "Wrong size on PyBuffAbility_10534402_K2_OnEndAbility");
static_assert(offsetof(PyBuffAbility_10534402_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyBuffAbility_10534402_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// PythonFunction PyAbility_105344.PyBuffAbility_10534402.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct PyBuffAbility_10534402_ReceiveTick final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBuffAbility_10534402_ReceiveTick) == 0x000004, "Wrong alignment on PyBuffAbility_10534402_ReceiveTick");
static_assert(sizeof(PyBuffAbility_10534402_ReceiveTick) == 0x000004, "Wrong size on PyBuffAbility_10534402_ReceiveTick");
static_assert(offsetof(PyBuffAbility_10534402_ReceiveTick, DeltaTime) == 0x000000, "Member 'PyBuffAbility_10534402_ReceiveTick::DeltaTime' has a wrong offset!");

// PythonFunction PyAbility_105344.PyCue_Buff_10534401.WhileActiveFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Buff_10534401_WhileActiveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Buff_10534401_WhileActiveFX) == 0x000008, "Wrong alignment on PyCue_Buff_10534401_WhileActiveFX");
static_assert(sizeof(PyCue_Buff_10534401_WhileActiveFX) == 0x0001C0, "Wrong size on PyCue_Buff_10534401_WhileActiveFX");
static_assert(offsetof(PyCue_Buff_10534401_WhileActiveFX, MyTarget) == 0x000000, "Member 'PyCue_Buff_10534401_WhileActiveFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Buff_10534401_WhileActiveFX, Parameters) == 0x000008, "Member 'PyCue_Buff_10534401_WhileActiveFX::Parameters' has a wrong offset!");

// PythonFunction PyAbility_105344.PyCue_Buff_10534401.OnRemoveFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Buff_10534401_OnRemoveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Buff_10534401_OnRemoveFX) == 0x000008, "Wrong alignment on PyCue_Buff_10534401_OnRemoveFX");
static_assert(sizeof(PyCue_Buff_10534401_OnRemoveFX) == 0x0001C0, "Wrong size on PyCue_Buff_10534401_OnRemoveFX");
static_assert(offsetof(PyCue_Buff_10534401_OnRemoveFX, MyTarget) == 0x000000, "Member 'PyCue_Buff_10534401_OnRemoveFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Buff_10534401_OnRemoveFX, Parameters) == 0x000008, "Member 'PyCue_Buff_10534401_OnRemoveFX::Parameters' has a wrong offset!");

// PythonFunction PyAbility_105344.PyCue_Buff_10534401.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct PyCue_Buff_10534401_ReceiveTick final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyCue_Buff_10534401_ReceiveTick) == 0x000004, "Wrong alignment on PyCue_Buff_10534401_ReceiveTick");
static_assert(sizeof(PyCue_Buff_10534401_ReceiveTick) == 0x000004, "Wrong size on PyCue_Buff_10534401_ReceiveTick");
static_assert(offsetof(PyCue_Buff_10534401_ReceiveTick, DeltaTime) == 0x000000, "Member 'PyCue_Buff_10534401_ReceiveTick::DeltaTime' has a wrong offset!");

// PythonFunction PyAbility_105344.PyCue_Buff_10534402.WhileActive
// 0x01C8 (0x01C8 - 0x0000)
struct PyCue_Buff_10534402_WhileActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
	bool                                          ReturnValue;                                       // 0x01C0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyCue_Buff_10534402_WhileActive) == 0x000008, "Wrong alignment on PyCue_Buff_10534402_WhileActive");
static_assert(sizeof(PyCue_Buff_10534402_WhileActive) == 0x0001C8, "Wrong size on PyCue_Buff_10534402_WhileActive");
static_assert(offsetof(PyCue_Buff_10534402_WhileActive, MyTarget) == 0x000000, "Member 'PyCue_Buff_10534402_WhileActive::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Buff_10534402_WhileActive, Parameters) == 0x000008, "Member 'PyCue_Buff_10534402_WhileActive::Parameters' has a wrong offset!");
static_assert(offsetof(PyCue_Buff_10534402_WhileActive, ReturnValue) == 0x0001C0, "Member 'PyCue_Buff_10534402_WhileActive::ReturnValue' has a wrong offset!");

// PythonFunction PyAbility_105344.PyCue_Buff_10534402.OnRemoveFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Buff_10534402_OnRemoveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Buff_10534402_OnRemoveFX) == 0x000008, "Wrong alignment on PyCue_Buff_10534402_OnRemoveFX");
static_assert(sizeof(PyCue_Buff_10534402_OnRemoveFX) == 0x0001C0, "Wrong size on PyCue_Buff_10534402_OnRemoveFX");
static_assert(offsetof(PyCue_Buff_10534402_OnRemoveFX, MyTarget) == 0x000000, "Member 'PyCue_Buff_10534402_OnRemoveFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Buff_10534402_OnRemoveFX, Parameters) == 0x000008, "Member 'PyCue_Buff_10534402_OnRemoveFX::Parameters' has a wrong offset!");

}

