#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104559

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_104559.PyCue_Scope_End_10455901.OnExecuteFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Scope_End_10455901_OnExecuteFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Scope_End_10455901_OnExecuteFX) == 0x000008, "Wrong alignment on PyCue_Scope_End_10455901_OnExecuteFX");
static_assert(sizeof(PyCue_Scope_End_10455901_OnExecuteFX) == 0x0001C0, "Wrong size on PyCue_Scope_End_10455901_OnExecuteFX");
static_assert(offsetof(PyCue_Scope_End_10455901_OnExecuteFX, MyTarget) == 0x000000, "Member 'PyCue_Scope_End_10455901_OnExecuteFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Scope_End_10455901_OnExecuteFX, Parameters) == 0x000008, "Member 'PyCue_Scope_End_10455901_OnExecuteFX::Parameters' has a wrong offset!");

// PythonFunction PyAbility_104559.PyAbility_104559.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_104559_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104559_CanActivate) == 0x000001, "Wrong alignment on PyAbility_104559_CanActivate");
static_assert(sizeof(PyAbility_104559_CanActivate) == 0x000001, "Wrong size on PyAbility_104559_CanActivate");
static_assert(offsetof(PyAbility_104559_CanActivate, ReturnValue) == 0x000000, "Member 'PyAbility_104559_CanActivate::ReturnValue' has a wrong offset!");

// PythonFunction PyAbility_104559.PyAbility_104559.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_104559_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104559_K2_OnEndAbility) == 0x000001, "Wrong alignment on PyAbility_104559_K2_OnEndAbility");
static_assert(sizeof(PyAbility_104559_K2_OnEndAbility) == 0x000001, "Wrong size on PyAbility_104559_K2_OnEndAbility");
static_assert(offsetof(PyAbility_104559_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'PyAbility_104559_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

// PythonFunction PyAbility_104559.PyAbility_104559.NativeOnMontageCompleted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104559_NativeOnMontageCompleted final
{
public:
	class FString                                 EventTag;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104559_NativeOnMontageCompleted) == 0x000008, "Wrong alignment on PyAbility_104559_NativeOnMontageCompleted");
static_assert(sizeof(PyAbility_104559_NativeOnMontageCompleted) == 0x000010, "Wrong size on PyAbility_104559_NativeOnMontageCompleted");
static_assert(offsetof(PyAbility_104559_NativeOnMontageCompleted, EventTag) == 0x000000, "Member 'PyAbility_104559_NativeOnMontageCompleted::EventTag' has a wrong offset!");

// PythonFunction PyAbility_104559.PyAbility_104559.NativeOnMontageEvent
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_104559_NativeOnMontageEvent final
{
public:
	class FString                                 EventTag;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyAbility_104559_NativeOnMontageEvent) == 0x000008, "Wrong alignment on PyAbility_104559_NativeOnMontageEvent");
static_assert(sizeof(PyAbility_104559_NativeOnMontageEvent) == 0x000010, "Wrong size on PyAbility_104559_NativeOnMontageEvent");
static_assert(offsetof(PyAbility_104559_NativeOnMontageEvent, EventTag) == 0x000000, "Member 'PyAbility_104559_NativeOnMontageEvent::EventTag' has a wrong offset!");

}

