#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102041

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_102041.PyCue_Buff_10204101.OnCharacterSculptChanged
// 0x0004 (0x0004 - 0x0000)
struct PyCue_Buff_10204101_OnCharacterSculptChanged final
{
public:
	int32                                         SculptID;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyCue_Buff_10204101_OnCharacterSculptChanged) == 0x000004, "Wrong alignment on PyCue_Buff_10204101_OnCharacterSculptChanged");
static_assert(sizeof(PyCue_Buff_10204101_OnCharacterSculptChanged) == 0x000004, "Wrong size on PyCue_Buff_10204101_OnCharacterSculptChanged");
static_assert(offsetof(PyCue_Buff_10204101_OnCharacterSculptChanged, SculptID) == 0x000000, "Member 'PyCue_Buff_10204101_OnCharacterSculptChanged::SculptID' has a wrong offset!");

// PythonFunction PyAbility_102041.PyCue_Buff_10204101.WhileActiveFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Buff_10204101_WhileActiveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Buff_10204101_WhileActiveFX) == 0x000008, "Wrong alignment on PyCue_Buff_10204101_WhileActiveFX");
static_assert(sizeof(PyCue_Buff_10204101_WhileActiveFX) == 0x0001C0, "Wrong size on PyCue_Buff_10204101_WhileActiveFX");
static_assert(offsetof(PyCue_Buff_10204101_WhileActiveFX, MyTarget) == 0x000000, "Member 'PyCue_Buff_10204101_WhileActiveFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Buff_10204101_WhileActiveFX, Parameters) == 0x000008, "Member 'PyCue_Buff_10204101_WhileActiveFX::Parameters' has a wrong offset!");

// PythonFunction PyAbility_102041.PyCue_Buff_10204101.OnRemoveFX
// 0x01C0 (0x01C0 - 0x0000)
struct PyCue_Buff_10204101_OnRemoveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x01B8)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PyCue_Buff_10204101_OnRemoveFX) == 0x000008, "Wrong alignment on PyCue_Buff_10204101_OnRemoveFX");
static_assert(sizeof(PyCue_Buff_10204101_OnRemoveFX) == 0x0001C0, "Wrong size on PyCue_Buff_10204101_OnRemoveFX");
static_assert(offsetof(PyCue_Buff_10204101_OnRemoveFX, MyTarget) == 0x000000, "Member 'PyCue_Buff_10204101_OnRemoveFX::MyTarget' has a wrong offset!");
static_assert(offsetof(PyCue_Buff_10204101_OnRemoveFX, Parameters) == 0x000008, "Member 'PyCue_Buff_10204101_OnRemoveFX::Parameters' has a wrong offset!");

}

