#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103031

#include "Basic.hpp"

#include "Hero_1030_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103031.PyCue_Ability_Loop_10303101
// 0x0008 (0x1000 - 0x0FF8)
class APyCue_Ability_Loop_10303101 final : public ACue_Ability_Loop_10303101
{
public:
	class UAnimSequence*                          MoonWeaponAnim;                                    // 0x0FF8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Loop_10303101">();
	}
	static class APyCue_Ability_Loop_10303101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Ability_Loop_10303101>();
	}
};
static_assert(alignof(APyCue_Ability_Loop_10303101) == 0x000008, "Wrong alignment on APyCue_Ability_Loop_10303101");
static_assert(sizeof(APyCue_Ability_Loop_10303101) == 0x001000, "Wrong size on APyCue_Ability_Loop_10303101");
static_assert(offsetof(APyCue_Ability_Loop_10303101, MoonWeaponAnim) == 0x000FF8, "Member 'APyCue_Ability_Loop_10303101::MoonWeaponAnim' has a wrong offset!");

}

