#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyActorEventPoint

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// PythonClass PyActorEventPoint.PyActorEventPoint
// 0x0050 (0x0698 - 0x0648)
class APyActorEventPoint final : public AGameplayActorBase
{
public:
	float                                         PosProgress;                                       // 0x0648(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           EventName;                                         // 0x064C(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasArgs;                                          // 0x0658(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_659[0x3];                                      // 0x0659(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         EventArgs;                                         // 0x065C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EventCount;                                        // 0x0660(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasListener;                                      // 0x0664(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_665[0x3];                                      // 0x0665(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 Listener;                                          // 0x0668(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsPreDes;                                         // 0x0670(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_671[0x7];                                      // 0x0671(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PreDesOldState;                                    // 0x0678(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 PreDesNewState;                                    // 0x0688(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void PyUpdatePosition();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyActorEventPoint">();
	}
	static class APyActorEventPoint* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyActorEventPoint>();
	}
};
static_assert(alignof(APyActorEventPoint) == 0x000008, "Wrong alignment on APyActorEventPoint");
static_assert(sizeof(APyActorEventPoint) == 0x000698, "Wrong size on APyActorEventPoint");
static_assert(offsetof(APyActorEventPoint, PosProgress) == 0x000648, "Member 'APyActorEventPoint::PosProgress' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, EventName) == 0x00064C, "Member 'APyActorEventPoint::EventName' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, bHasArgs) == 0x000658, "Member 'APyActorEventPoint::bHasArgs' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, EventArgs) == 0x00065C, "Member 'APyActorEventPoint::EventArgs' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, EventCount) == 0x000660, "Member 'APyActorEventPoint::EventCount' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, bHasListener) == 0x000664, "Member 'APyActorEventPoint::bHasListener' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, Listener) == 0x000668, "Member 'APyActorEventPoint::Listener' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, bIsPreDes) == 0x000670, "Member 'APyActorEventPoint::bIsPreDes' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, PreDesOldState) == 0x000678, "Member 'APyActorEventPoint::PreDesOldState' has a wrong offset!");
static_assert(offsetof(APyActorEventPoint, PreDesNewState) == 0x000688, "Member 'APyActorEventPoint::PreDesNewState' has a wrong offset!");

}

