#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAISelectTarget_GrootWoodWall

#include "Basic.hpp"

#include "PyAISelectTarget_SelectGroundPoint_classes.hpp"


namespace SDK
{

// PythonClass PyAISelectTarget_GrootWoodWall.PyAISelectTarget_GrootSetWoodWall_Defend
// 0x0010 (0x1110 - 0x1100)
class UPyAISelectTarget_GrootSetWoodWall_Defend : public UPyAISelectTarget_SelectGroundPointInRange
{
public:
	float                                         LowHealthPercent;                                  // 0x1100(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TeammateRange;                                     // 0x1104(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAISelectTarget_GrootSetWoodWall_Defend">();
	}
	static class UPyAISelectTarget_GrootSetWoodWall_Defend* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAISelectTarget_GrootSetWoodWall_Defend>();
	}
};
static_assert(alignof(UPyAISelectTarget_GrootSetWoodWall_Defend) == 0x000010, "Wrong alignment on UPyAISelectTarget_GrootSetWoodWall_Defend");
static_assert(sizeof(UPyAISelectTarget_GrootSetWoodWall_Defend) == 0x001110, "Wrong size on UPyAISelectTarget_GrootSetWoodWall_Defend");
static_assert(offsetof(UPyAISelectTarget_GrootSetWoodWall_Defend, LowHealthPercent) == 0x001100, "Member 'UPyAISelectTarget_GrootSetWoodWall_Defend::LowHealthPercent' has a wrong offset!");
static_assert(offsetof(UPyAISelectTarget_GrootSetWoodWall_Defend, TeammateRange) == 0x001104, "Member 'UPyAISelectTarget_GrootSetWoodWall_Defend::TeammateRange' has a wrong offset!");

// PythonClass PyAISelectTarget_GrootWoodWall.PyAISelectTarget_GrootSetWoodWall_Distrub
// 0x0000 (0x1100 - 0x1100)
class UPyAISelectTarget_GrootSetWoodWall_Distrub : public UPyAISelectTarget_SelectGroundPointInRange
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAISelectTarget_GrootSetWoodWall_Distrub">();
	}
	static class UPyAISelectTarget_GrootSetWoodWall_Distrub* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAISelectTarget_GrootSetWoodWall_Distrub>();
	}
};
static_assert(alignof(UPyAISelectTarget_GrootSetWoodWall_Distrub) == 0x000010, "Wrong alignment on UPyAISelectTarget_GrootSetWoodWall_Distrub");
static_assert(sizeof(UPyAISelectTarget_GrootSetWoodWall_Distrub) == 0x001100, "Wrong size on UPyAISelectTarget_GrootSetWoodWall_Distrub");

// PythonClass PyAISelectTarget_GrootWoodWall.PyAISelectTarget_GrootWoodWall_Test
// 0x0010 (0x1100 - 0x10F0)
class UPyAISelectTarget_GrootWoodWall_Test final : public UPyAISelectTarget_SelectGroundPointBase
{
public:
	float                                         OffsetDist;                                        // 0x10F0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAISelectTarget_GrootWoodWall_Test">();
	}
	static class UPyAISelectTarget_GrootWoodWall_Test* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAISelectTarget_GrootWoodWall_Test>();
	}
};
static_assert(alignof(UPyAISelectTarget_GrootWoodWall_Test) == 0x000010, "Wrong alignment on UPyAISelectTarget_GrootWoodWall_Test");
static_assert(sizeof(UPyAISelectTarget_GrootWoodWall_Test) == 0x001100, "Wrong size on UPyAISelectTarget_GrootWoodWall_Test");
static_assert(offsetof(UPyAISelectTarget_GrootWoodWall_Test, OffsetDist) == 0x0010F0, "Member 'UPyAISelectTarget_GrootWoodWall_Test::OffsetDist' has a wrong offset!");

}

