#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBenjaminGrimCharacter

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyBenjaminGrimCharacter.PyBenjaminGrimAnimInstance.AnimNotify_DashFootstep_Left
// 0x0008 (0x0008 - 0x0000)
struct PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Left final
{
public:
	class UAnimNotify*                            Notify;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Left) == 0x000008, "Wrong alignment on PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Left");
static_assert(sizeof(PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Left) == 0x000008, "Wrong size on PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Left");
static_assert(offsetof(PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Left, Notify) == 0x000000, "Member 'PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Left::Notify' has a wrong offset!");

// PythonFunction PyBenjaminGrimCharacter.PyBenjaminGrimAnimInstance.AnimNotify_DashFootstep_Right
// 0x0008 (0x0008 - 0x0000)
struct PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Right final
{
public:
	class UAnimNotify*                            Notify;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Right) == 0x000008, "Wrong alignment on PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Right");
static_assert(sizeof(PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Right) == 0x000008, "Wrong size on PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Right");
static_assert(offsetof(PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Right, Notify) == 0x000000, "Member 'PyBenjaminGrimAnimInstance_AnimNotify_DashFootstep_Right::Notify' has a wrong offset!");

}

