#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffRuleComponent

#include "Basic.hpp"

#include "MarvelLevel_structs.hpp"
#include "MarvelLevel_classes.hpp"
#include "PyRuleComponent_classes.hpp"


namespace SDK
{

// PythonClass PyBuffRuleComponent.PyBuffRuleConfig
// 0x0010 (0x0040 - 0x0030)
class UPyBuffRuleConfig final : public UMarvelRuleConfig
{
public:
	TArray<struct FBuffRuleCompConfigItem>        BuffConfs;                                         // 0x0030(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyBuffRuleConfig">();
	}
	static class UPyBuffRuleConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffRuleConfig>();
	}
};
static_assert(alignof(UPyBuffRuleConfig) == 0x000008, "Wrong alignment on UPyBuffRuleConfig");
static_assert(sizeof(UPyBuffRuleConfig) == 0x000040, "Wrong size on UPyBuffRuleConfig");
static_assert(offsetof(UPyBuffRuleConfig, BuffConfs) == 0x000030, "Member 'UPyBuffRuleConfig::BuffConfs' has a wrong offset!");

// PythonClass PyBuffRuleComponent.PyBuffRuleComponent
// 0x0010 (0x0100 - 0x00F0)
class UPyBuffRuleComponent final : public UPyRuleComponent
{
public:
	TArray<struct FBuffRuleCompConfigItem>        BuffConfs;                                         // 0x00F0(0x0010)(BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyBuffRuleComponent">();
	}
	static class UPyBuffRuleComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffRuleComponent>();
	}
};
static_assert(alignof(UPyBuffRuleComponent) == 0x000008, "Wrong alignment on UPyBuffRuleComponent");
static_assert(sizeof(UPyBuffRuleComponent) == 0x000100, "Wrong size on UPyBuffRuleComponent");
static_assert(offsetof(UPyBuffRuleComponent, BuffConfs) == 0x0000F0, "Member 'UPyBuffRuleComponent::BuffConfs' has a wrong offset!");

}

