#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyCue_Buff_10122001

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// PythonClass PyCue_Buff_10122001.PyCue_Buff_10122001
// 0x0198 (0x13A8 - 0x1210)
class APyCue_Buff_10122001 final : public AMarvelCueNotify_Buff
{
public:
	class UFXSystemAsset*                         BeHitEffectAsset;                                  // 0x1210(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 BeHitEffectAttachSocketName;                       // 0x1218(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                BeHitEffectLocationOffset;                         // 0x1228(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          HitAudio;                                          // 0x1240(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         HeadChangedEffectAsset;                            // 0x1248(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 HeadChangedAttachSocketName;                       // 0x1250(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                HeadChangedLocationOffset;                         // 0x1260(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<int32, struct FVector>                   SpecialHeroLocationOffsetMap;                      // 0x1278(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	int32                                         HeadChangedAudioID;                                // 0x12C8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12CC[0x4];                                     // 0x12CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemAsset*                         HeadChangedBiggestEffectAsset;                     // 0x12D0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          HeadChangedAudio;                                  // 0x12D8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          HeadChangedBiggestAudio;                           // 0x12E0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          HeadChangedBiggestLoopAudio;                       // 0x12E8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HitEffectDivisor;                                  // 0x12F0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HeadChangedpEffectDivisor;                         // 0x12F4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HeadChangedBiggestEffectDivisor;                   // 0x12F8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LoopEffectDivisor;                                 // 0x12FC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<int32, float>                            SpecialHeroInstantEffectDivisorMap;                // 0x1300(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	TMap<int32, float>                            SpecialHeroLoopEffectDivisorMap;                   // 0x1350(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	float                                         HitEffectPlayInterval;                             // 0x13A0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HeadChangedpEffectPlayInterval;                    // 0x13A4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnCharacterSculptChanged(int32 SculptID);
	void OnInstantEffect(bool IsMax, float NewScale);
	void OnSustainedEffect(bool Visibility);
	void OnPostTakeDamage(class AActor* Source_avatar, class AActor* Target_avatar, const struct FAttributeModifierHandle& Attribute_modifier_handle);
	void OnViewTargetChangeEvent(class AActor* InActor);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Buff_10122001">();
	}
	static class APyCue_Buff_10122001* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_10122001>();
	}
};
static_assert(alignof(APyCue_Buff_10122001) == 0x000008, "Wrong alignment on APyCue_Buff_10122001");
static_assert(sizeof(APyCue_Buff_10122001) == 0x0013A8, "Wrong size on APyCue_Buff_10122001");
static_assert(offsetof(APyCue_Buff_10122001, BeHitEffectAsset) == 0x001210, "Member 'APyCue_Buff_10122001::BeHitEffectAsset' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, BeHitEffectAttachSocketName) == 0x001218, "Member 'APyCue_Buff_10122001::BeHitEffectAttachSocketName' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, BeHitEffectLocationOffset) == 0x001228, "Member 'APyCue_Buff_10122001::BeHitEffectLocationOffset' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HitAudio) == 0x001240, "Member 'APyCue_Buff_10122001::HitAudio' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedEffectAsset) == 0x001248, "Member 'APyCue_Buff_10122001::HeadChangedEffectAsset' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedAttachSocketName) == 0x001250, "Member 'APyCue_Buff_10122001::HeadChangedAttachSocketName' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedLocationOffset) == 0x001260, "Member 'APyCue_Buff_10122001::HeadChangedLocationOffset' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, SpecialHeroLocationOffsetMap) == 0x001278, "Member 'APyCue_Buff_10122001::SpecialHeroLocationOffsetMap' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedAudioID) == 0x0012C8, "Member 'APyCue_Buff_10122001::HeadChangedAudioID' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedBiggestEffectAsset) == 0x0012D0, "Member 'APyCue_Buff_10122001::HeadChangedBiggestEffectAsset' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedAudio) == 0x0012D8, "Member 'APyCue_Buff_10122001::HeadChangedAudio' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedBiggestAudio) == 0x0012E0, "Member 'APyCue_Buff_10122001::HeadChangedBiggestAudio' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedBiggestLoopAudio) == 0x0012E8, "Member 'APyCue_Buff_10122001::HeadChangedBiggestLoopAudio' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HitEffectDivisor) == 0x0012F0, "Member 'APyCue_Buff_10122001::HitEffectDivisor' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedpEffectDivisor) == 0x0012F4, "Member 'APyCue_Buff_10122001::HeadChangedpEffectDivisor' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedBiggestEffectDivisor) == 0x0012F8, "Member 'APyCue_Buff_10122001::HeadChangedBiggestEffectDivisor' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, LoopEffectDivisor) == 0x0012FC, "Member 'APyCue_Buff_10122001::LoopEffectDivisor' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, SpecialHeroInstantEffectDivisorMap) == 0x001300, "Member 'APyCue_Buff_10122001::SpecialHeroInstantEffectDivisorMap' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, SpecialHeroLoopEffectDivisorMap) == 0x001350, "Member 'APyCue_Buff_10122001::SpecialHeroLoopEffectDivisorMap' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HitEffectPlayInterval) == 0x0013A0, "Member 'APyCue_Buff_10122001::HitEffectPlayInterval' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_10122001, HeadChangedpEffectPlayInterval) == 0x0013A4, "Member 'APyCue_Buff_10122001::HeadChangedpEffectPlayInterval' has a wrong offset!");

}

