#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyCue_Ability_Loop_10185101

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyCue_Ability_Loop_10185101.PyCue_Ability_Loop_10185101
// 0x0010 (0x1000 - 0x0FF0)
class APyCue_Ability_Loop_10185101 final : public AMarvelCueNotify_Ability
{
public:
	class UAnimMontage*                           LimbsMontage;                                      // 0x0FF0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAnimSequence*                          LimbsIdleAnim;                                     // 0x0FF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Loop_10185101">();
	}
	static class APyCue_Ability_Loop_10185101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Ability_Loop_10185101>();
	}
};
static_assert(alignof(APyCue_Ability_Loop_10185101) == 0x000008, "Wrong alignment on APyCue_Ability_Loop_10185101");
static_assert(sizeof(APyCue_Ability_Loop_10185101) == 0x001000, "Wrong size on APyCue_Ability_Loop_10185101");
static_assert(offsetof(APyCue_Ability_Loop_10185101, LimbsMontage) == 0x000FF0, "Member 'APyCue_Ability_Loop_10185101::LimbsMontage' has a wrong offset!");
static_assert(offsetof(APyCue_Ability_Loop_10185101, LimbsIdleAnim) == 0x000FF8, "Member 'APyCue_Ability_Loop_10185101::LimbsIdleAnim' has a wrong offset!");

}

