#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyDoorSkeletalMesh

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass PyDoorSkeletalMesh.PyDoorMesh
// 0x0030 (0x06A8 - 0x0678)
class APyDoorMesh final : public ASkeletalMeshActor
{
public:
	int32                                         OpenState;                                         // 0x0678(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_67C[0x4];                                      // 0x067C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                DeltaMove;                                         // 0x0680(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AnimSpeed;                                         // 0x0698(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Delay;                                             // 0x069C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AudioEvent;                                        // 0x06A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void OnPlayOpenDoorAnim();
	void StartPlayOpenDoorAnim();
	void SetDoorsProgress();
	void OnRep_OpenState();
	void S_payload_reach(const struct FGameplayTag& Event_name, float Event_args);
	void PlaySkeletalMeshAnim();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyDoorMesh">();
	}
	static class APyDoorMesh* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyDoorMesh>();
	}
};
static_assert(alignof(APyDoorMesh) == 0x000008, "Wrong alignment on APyDoorMesh");
static_assert(sizeof(APyDoorMesh) == 0x0006A8, "Wrong size on APyDoorMesh");
static_assert(offsetof(APyDoorMesh, OpenState) == 0x000678, "Member 'APyDoorMesh::OpenState' has a wrong offset!");
static_assert(offsetof(APyDoorMesh, DeltaMove) == 0x000680, "Member 'APyDoorMesh::DeltaMove' has a wrong offset!");
static_assert(offsetof(APyDoorMesh, AnimSpeed) == 0x000698, "Member 'APyDoorMesh::AnimSpeed' has a wrong offset!");
static_assert(offsetof(APyDoorMesh, Delay) == 0x00069C, "Member 'APyDoorMesh::Delay' has a wrong offset!");
static_assert(offsetof(APyDoorMesh, AudioEvent) == 0x0006A0, "Member 'APyDoorMesh::AudioEvent' has a wrong offset!");

}

