#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyDownloadImageManager

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// PythonClass PyDownloadImageManager.PyDownloadImageManger
// 0x0010 (0x0040 - 0x0030)
class UPyDownloadImageManger final : public UObject
{
public:
	TArray<class UTexture2DDynamic*>              ImageList;                                         // 0x0030(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyDownloadImageManger">();
	}
	static class UPyDownloadImageManger* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyDownloadImageManger>();
	}
};
static_assert(alignof(UPyDownloadImageManger) == 0x000008, "Wrong alignment on UPyDownloadImageManger");
static_assert(sizeof(UPyDownloadImageManger) == 0x000040, "Wrong size on UPyDownloadImageManger");
static_assert(offsetof(UPyDownloadImageManger, ImageList) == 0x000030, "Member 'UPyDownloadImageManger::ImageList' has a wrong offset!");

}

