#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyExtension_ListView

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyExtension_ListView.PyExtension_ListView
// 0x0000 (0x0030 - 0x0030)
class UPyExtension_ListView final : public UMarvelUserWidgetExtension
{
public:
	void BP_Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyExtension_ListView">();
	}
	static class UPyExtension_ListView* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyExtension_ListView>();
	}
};
static_assert(alignof(UPyExtension_ListView) == 0x000008, "Wrong alignment on UPyExtension_ListView");
static_assert(sizeof(UPyExtension_ListView) == 0x000030, "Wrong size on UPyExtension_ListView");

}

