#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyExtension_MainPanelEntry

#include "Basic.hpp"

#include "PyExtension_LayerWidgetEntry_classes.hpp"


namespace SDK
{

// PythonClass PyExtension_MainPanelEntry.PyExtension_MainPanelEntry
// 0x0000 (0x0050 - 0x0050)
class UPyExtension_MainPanelEntry final : public UPyExtension_LayerWidgetEntry
{
public:
	void BP_OnInitialize();
	void BP_OnVisibleChanged(bool bNewVisible);
	void BP_OnCascadingVisibleChanged(bool bNewVisible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyExtension_MainPanelEntry">();
	}
	static class UPyExtension_MainPanelEntry* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyExtension_MainPanelEntry>();
	}
};
static_assert(alignof(UPyExtension_MainPanelEntry) == 0x000008, "Wrong alignment on UPyExtension_MainPanelEntry");
static_assert(sizeof(UPyExtension_MainPanelEntry) == 0x000050, "Wrong size on UPyExtension_MainPanelEntry");

}

