#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyHeroSwitchRuleComponent_TimeoutRandom

#include "Basic.hpp"

#include "PyHeroSwitchRuleComponent_TimeoutRandom_classes.hpp"


namespace SDK
{

// PythonFunction PyHeroSwitchRuleComponent_TimeoutRandom.PyHeroSwitchConfig_TimeoutRandom.PyPostInitProperties
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyHeroSwitchConfig_TimeoutRandom::PyPostInitProperties()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyHeroSwitchConfig_TimeoutRandom", "PyPostInitProperties");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

