#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyHumanTorchActor

#include "Basic.hpp"

#include "Hero_1017_classes.hpp"


namespace SDK
{

// PythonClass PyHumanTorchActor.PyHumanTorchChildActor
// 0x0000 (0x0F50 - 0x0F50)
class APyHumanTorchChildActor final : public AHumanTorchChildActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyHumanTorchChildActor">();
	}
	static class APyHumanTorchChildActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyHumanTorchChildActor>();
	}
};
static_assert(alignof(APyHumanTorchChildActor) == 0x000008, "Wrong alignment on APyHumanTorchChildActor");
static_assert(sizeof(APyHumanTorchChildActor) == 0x000F50, "Wrong size on APyHumanTorchChildActor");

// PythonClass PyHumanTorchActor.PyHumanTorchCharacter
// 0x0000 (0x1C40 - 0x1C40)
class APyHumanTorchCharacter : public AHumanTorchCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyHumanTorchCharacter">();
	}
	static class APyHumanTorchCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyHumanTorchCharacter>();
	}
};
static_assert(alignof(APyHumanTorchCharacter) == 0x000010, "Wrong alignment on APyHumanTorchCharacter");
static_assert(sizeof(APyHumanTorchCharacter) == 0x001C40, "Wrong size on APyHumanTorchCharacter");

}

