#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelLokiPhantomNodes

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyLevelLokiPhantomNodes.PyLokiPhantomManagerComponent
// 0x0058 (0x0148 - 0x00F0)
class UPyLokiPhantomManagerComponent final : public UActorComponent
{
public:
	class UClass*                                 LokiPhantomClass;                                  // 0x00F0(0x0008)(Net, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FirstDelayAppearTime;                              // 0x00F8(0x0004)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SecondDelayAppearTime;                             // 0x00FC(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         UpdateInterval;                                    // 0x0100(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 MaterialParameterName;                             // 0x0108(0x0010)(Net, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaterialVisibleValue;                              // 0x0118(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaterialInvisibleValue;                            // 0x011C(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaterialAppearTime;                                // 0x0120(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaterialDisappearTime;                             // 0x0124(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 NiagaraParameterName;                              // 0x0128(0x0010)(Net, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NiagaraVisibleValue;                               // 0x0138(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NiagaraInvisibleValue;                             // 0x013C(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NiagaraDisappearTime;                              // 0x0140(0x0004)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static void LokiPhantomInitialize(class AActor* ProcessController, float FirstDelayAppearTime_0, float SecondDelayAppearTime_0, float UpdateInterval_0, const class FString& MaterialParameterName_0, float MaterialVisibleValue_0, float MaterialInvisibleValue_0, float MaterialAppearTime_0, float MaterialDisappearTime_0, const class FString& NiagaraParameterName_0, float NiagaraVisibleValue_0, float NiagaraInvisibleValue_0, float NiagaraDisappearTime_0);

	void ReceiveBeginPlay();
	void OnRep_FirstDelayAppearTime();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLokiPhantomManagerComponent">();
	}
	static class UPyLokiPhantomManagerComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyLokiPhantomManagerComponent>();
	}
};
static_assert(alignof(UPyLokiPhantomManagerComponent) == 0x000008, "Wrong alignment on UPyLokiPhantomManagerComponent");
static_assert(sizeof(UPyLokiPhantomManagerComponent) == 0x000148, "Wrong size on UPyLokiPhantomManagerComponent");
static_assert(offsetof(UPyLokiPhantomManagerComponent, LokiPhantomClass) == 0x0000F0, "Member 'UPyLokiPhantomManagerComponent::LokiPhantomClass' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, FirstDelayAppearTime) == 0x0000F8, "Member 'UPyLokiPhantomManagerComponent::FirstDelayAppearTime' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, SecondDelayAppearTime) == 0x0000FC, "Member 'UPyLokiPhantomManagerComponent::SecondDelayAppearTime' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, UpdateInterval) == 0x000100, "Member 'UPyLokiPhantomManagerComponent::UpdateInterval' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, MaterialParameterName) == 0x000108, "Member 'UPyLokiPhantomManagerComponent::MaterialParameterName' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, MaterialVisibleValue) == 0x000118, "Member 'UPyLokiPhantomManagerComponent::MaterialVisibleValue' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, MaterialInvisibleValue) == 0x00011C, "Member 'UPyLokiPhantomManagerComponent::MaterialInvisibleValue' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, MaterialAppearTime) == 0x000120, "Member 'UPyLokiPhantomManagerComponent::MaterialAppearTime' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, MaterialDisappearTime) == 0x000124, "Member 'UPyLokiPhantomManagerComponent::MaterialDisappearTime' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, NiagaraParameterName) == 0x000128, "Member 'UPyLokiPhantomManagerComponent::NiagaraParameterName' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, NiagaraVisibleValue) == 0x000138, "Member 'UPyLokiPhantomManagerComponent::NiagaraVisibleValue' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, NiagaraInvisibleValue) == 0x00013C, "Member 'UPyLokiPhantomManagerComponent::NiagaraInvisibleValue' has a wrong offset!");
static_assert(offsetof(UPyLokiPhantomManagerComponent, NiagaraDisappearTime) == 0x000140, "Member 'UPyLokiPhantomManagerComponent::NiagaraDisappearTime' has a wrong offset!");

// PythonClass PyLevelLokiPhantomNodes.PyLokiPhantom
// 0x0080 (0x06A8 - 0x0628)
class APyLokiPhantom final : public ALevelNPCActor
{
public:
	class UNiagaraSystem*                         Niagara;                                           // 0x0628(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AppearAkEvent;                                     // 0x0630(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          LoopAkEvent;                                       // 0x0638(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          DisappearAkEvent;                                  // 0x0640(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<int32>                                 BasicVoice;                                        // 0x0648(0x0010)(Edit, NativeAccessSpecifierPublic)
	TMap<int32, TArray<int32>>                    SpecialVoice;                                      // 0x0658(0x0050)(Edit, NativeAccessSpecifierPublic)

public:
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLokiPhantom">();
	}
	static class APyLokiPhantom* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyLokiPhantom>();
	}
};
static_assert(alignof(APyLokiPhantom) == 0x000008, "Wrong alignment on APyLokiPhantom");
static_assert(sizeof(APyLokiPhantom) == 0x0006A8, "Wrong size on APyLokiPhantom");
static_assert(offsetof(APyLokiPhantom, Niagara) == 0x000628, "Member 'APyLokiPhantom::Niagara' has a wrong offset!");
static_assert(offsetof(APyLokiPhantom, AppearAkEvent) == 0x000630, "Member 'APyLokiPhantom::AppearAkEvent' has a wrong offset!");
static_assert(offsetof(APyLokiPhantom, LoopAkEvent) == 0x000638, "Member 'APyLokiPhantom::LoopAkEvent' has a wrong offset!");
static_assert(offsetof(APyLokiPhantom, DisappearAkEvent) == 0x000640, "Member 'APyLokiPhantom::DisappearAkEvent' has a wrong offset!");
static_assert(offsetof(APyLokiPhantom, BasicVoice) == 0x000648, "Member 'APyLokiPhantom::BasicVoice' has a wrong offset!");
static_assert(offsetof(APyLokiPhantom, SpecialVoice) == 0x000658, "Member 'APyLokiPhantom::SpecialVoice' has a wrong offset!");

}

