#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelProcessController

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "MarvelLevel_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PyLevelProcessController.PyLevelProcessController
// 0x0080 (0x0678 - 0x05F8)
class APyLevelProcessController : public AMarvelLevelProcessController
{
public:
	bool                                          bIsGroupActorsMoving;                              // 0x05F8(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5F9[0x7];                                      // 0x05F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CurrentPartName;                                   // 0x0600(0x0010)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, RepNotify, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCameraInterp*                          EnterCameraInterp;                                 // 0x0610(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraSystem*                         EnterEffect;                                       // 0x0618(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          EnterAudio;                                        // 0x0620(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSoftObjectPath>                SoftReferencedSelectHeroLevels;                    // 0x0628(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             PrepareStartDispatcher;                            // 0x0638(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             PrepareEndDispatcher;                              // 0x0648(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             FightStartDispatcher;                              // 0x0658(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             FightEndDispatcher;                                // 0x0668(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	static class AMarvelLevelProcessController* GetProcessController(class AActor* WCO);

	void PrepareStartDispatcher__DelegateSignature();
	void PrepareEndDispatcher__DelegateSignature();
	void FightStartDispatcher__DelegateSignature();
	void FightEndDispatcher__DelegateSignature();
	void ReceiveInit();
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void OnMapLoaded();
	void OnBeginPlay();
	void OnMatchStateChanged(EMatchState MatchState);
	class FString GetCurrentLevelPartName();
	void OnModeTimeOut();
	void EndCurrentLevel(const TArray<EBattleSide>& Win_side_list);
	void SkyCrackWaveTest();
	void LokiPhantomAppear();
	void LokiPhantomDisappear();
	void SetGroupActorsMoveState(bool IsMoving);
	void OnRep_IsGroupActorsMoving();
	void OnRep_CurrentPartName();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelProcessController">();
	}
	static class APyLevelProcessController* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyLevelProcessController>();
	}
};
static_assert(alignof(APyLevelProcessController) == 0x000008, "Wrong alignment on APyLevelProcessController");
static_assert(sizeof(APyLevelProcessController) == 0x000678, "Wrong size on APyLevelProcessController");
static_assert(offsetof(APyLevelProcessController, bIsGroupActorsMoving) == 0x0005F8, "Member 'APyLevelProcessController::bIsGroupActorsMoving' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, CurrentPartName) == 0x000600, "Member 'APyLevelProcessController::CurrentPartName' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, EnterCameraInterp) == 0x000610, "Member 'APyLevelProcessController::EnterCameraInterp' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, EnterEffect) == 0x000618, "Member 'APyLevelProcessController::EnterEffect' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, EnterAudio) == 0x000620, "Member 'APyLevelProcessController::EnterAudio' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, SoftReferencedSelectHeroLevels) == 0x000628, "Member 'APyLevelProcessController::SoftReferencedSelectHeroLevels' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, PrepareStartDispatcher) == 0x000638, "Member 'APyLevelProcessController::PrepareStartDispatcher' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, PrepareEndDispatcher) == 0x000648, "Member 'APyLevelProcessController::PrepareEndDispatcher' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, FightStartDispatcher) == 0x000658, "Member 'APyLevelProcessController::FightStartDispatcher' has a wrong offset!");
static_assert(offsetof(APyLevelProcessController, FightEndDispatcher) == 0x000668, "Member 'APyLevelProcessController::FightEndDispatcher' has a wrong offset!");

}

