#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelLokiPhantomNodes

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyLevelLokiPhantomNodes.PyLokiPhantomManagerComponent.LokiPhantomInitialize
// 0x0058 (0x0058 - 0x0000)
struct PyLokiPhantomManagerComponent_LokiPhantomInitialize final
{
public:
	class AActor*                                 ProcessController;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         FirstDelayAppearTime_0;                            // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SecondDelayAppearTime_0;                           // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         UpdateInterval_0;                                  // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 MaterialParameterName_0;                           // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	float                                         MaterialVisibleValue_0;                            // 0x0028(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaterialInvisibleValue_0;                          // 0x002C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaterialAppearTime_0;                              // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaterialDisappearTime_0;                           // 0x0034(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 NiagaraParameterName_0;                            // 0x0038(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	float                                         NiagaraVisibleValue_0;                             // 0x0048(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         NiagaraInvisibleValue_0;                           // 0x004C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         NiagaraDisappearTime_0;                            // 0x0050(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyLokiPhantomManagerComponent_LokiPhantomInitialize) == 0x000008, "Wrong alignment on PyLokiPhantomManagerComponent_LokiPhantomInitialize");
static_assert(sizeof(PyLokiPhantomManagerComponent_LokiPhantomInitialize) == 0x000058, "Wrong size on PyLokiPhantomManagerComponent_LokiPhantomInitialize");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, ProcessController) == 0x000000, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::ProcessController' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, FirstDelayAppearTime_0) == 0x000008, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::FirstDelayAppearTime_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, SecondDelayAppearTime_0) == 0x00000C, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::SecondDelayAppearTime_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, UpdateInterval_0) == 0x000010, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::UpdateInterval_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, MaterialParameterName_0) == 0x000018, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::MaterialParameterName_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, MaterialVisibleValue_0) == 0x000028, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::MaterialVisibleValue_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, MaterialInvisibleValue_0) == 0x00002C, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::MaterialInvisibleValue_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, MaterialAppearTime_0) == 0x000030, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::MaterialAppearTime_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, MaterialDisappearTime_0) == 0x000034, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::MaterialDisappearTime_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, NiagaraParameterName_0) == 0x000038, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::NiagaraParameterName_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, NiagaraVisibleValue_0) == 0x000048, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::NiagaraVisibleValue_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, NiagaraInvisibleValue_0) == 0x00004C, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::NiagaraInvisibleValue_0' has a wrong offset!");
static_assert(offsetof(PyLokiPhantomManagerComponent_LokiPhantomInitialize, NiagaraDisappearTime_0) == 0x000050, "Member 'PyLokiPhantomManagerComponent_LokiPhantomInitialize::NiagaraDisappearTime_0' has a wrong offset!");

// PythonFunction PyLevelLokiPhantomNodes.PyLokiPhantomManagerComponent.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyLokiPhantomManagerComponent_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyLokiPhantomManagerComponent_ReceiveEndPlay) == 0x000001, "Wrong alignment on PyLokiPhantomManagerComponent_ReceiveEndPlay");
static_assert(sizeof(PyLokiPhantomManagerComponent_ReceiveEndPlay) == 0x000001, "Wrong size on PyLokiPhantomManagerComponent_ReceiveEndPlay");
static_assert(offsetof(PyLokiPhantomManagerComponent_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'PyLokiPhantomManagerComponent_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// PythonFunction PyLevelLokiPhantomNodes.PyLokiPhantom.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyLokiPhantom_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyLokiPhantom_ReceiveEndPlay) == 0x000001, "Wrong alignment on PyLokiPhantom_ReceiveEndPlay");
static_assert(sizeof(PyLokiPhantom_ReceiveEndPlay) == 0x000001, "Wrong size on PyLokiPhantom_ReceiveEndPlay");
static_assert(offsetof(PyLokiPhantom_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'PyLokiPhantom_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

}

