#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLegalZone

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "MarvelLevel_structs.hpp"
#include "DeclarativeUnreal_structs.hpp"


namespace SDK
{

// PythonClass PyLegalZone.PyLegalZone
// 0x0078 (0x06F0 - 0x0678)
class APyLegalZone final : public AControlPointBase
{
public:
	int32                                         LegalZoneState;                                    // 0x0678(0x0004)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBattleSide                                   BattleSide;                                        // 0x067C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_67D[0x3];                                      // 0x067D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         BirthBases;                                        // 0x0680(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FVector                                CrystalLocation;                                   // 0x0690(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 Altar;                                             // 0x06A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APyLevelSequenceActor*                  AltarSequence;                                     // 0x06B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           CueTag;                                            // 0x06B8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6C4[0x4];                                      // 0x06C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Index_0;                                           // 0x06C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOwnershipType                                OcuppySide;                                        // 0x06D8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6D9[0x7];                                      // 0x06D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnLegalZoneStateChanged;                           // 0x06E0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnLegalZoneStateChanged__DelegateSignature();
	void ReceiveInit();
	void ReceiveBeginPlay();
	void OnPrepareStartDispatcher();
	void OnTimeCrystalStateChanged(EInfinityCrisisState OldState, EInfinityCrisisState NewState, EOwnershipType OldSie, EOwnershipType NewSide);
	void OnRep_LegalZoneState();
	void ReceiveDestroyed();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLegalZone">();
	}
	static class APyLegalZone* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyLegalZone>();
	}
};
static_assert(alignof(APyLegalZone) == 0x000008, "Wrong alignment on APyLegalZone");
static_assert(sizeof(APyLegalZone) == 0x0006F0, "Wrong size on APyLegalZone");
static_assert(offsetof(APyLegalZone, LegalZoneState) == 0x000678, "Member 'APyLegalZone::LegalZoneState' has a wrong offset!");
static_assert(offsetof(APyLegalZone, BattleSide) == 0x00067C, "Member 'APyLegalZone::BattleSide' has a wrong offset!");
static_assert(offsetof(APyLegalZone, BirthBases) == 0x000680, "Member 'APyLegalZone::BirthBases' has a wrong offset!");
static_assert(offsetof(APyLegalZone, CrystalLocation) == 0x000690, "Member 'APyLegalZone::CrystalLocation' has a wrong offset!");
static_assert(offsetof(APyLegalZone, Altar) == 0x0006A8, "Member 'APyLegalZone::Altar' has a wrong offset!");
static_assert(offsetof(APyLegalZone, AltarSequence) == 0x0006B0, "Member 'APyLegalZone::AltarSequence' has a wrong offset!");
static_assert(offsetof(APyLegalZone, CueTag) == 0x0006B8, "Member 'APyLegalZone::CueTag' has a wrong offset!");
static_assert(offsetof(APyLegalZone, Index_0) == 0x0006C8, "Member 'APyLegalZone::Index_0' has a wrong offset!");
static_assert(offsetof(APyLegalZone, OcuppySide) == 0x0006D8, "Member 'APyLegalZone::OcuppySide' has a wrong offset!");
static_assert(offsetof(APyLegalZone, OnLegalZoneStateChanged) == 0x0006E0, "Member 'APyLegalZone::OnLegalZoneStateChanged' has a wrong offset!");

// PythonClass PyLegalZone.PyCue_Level_LegalZone
// 0x00B8 (0x1120 - 0x1068)
class APyCue_Level_LegalZone final : public AMarvelCueNotify_Loop
{
public:
	class UMaterialInstance*                      MaterialColorWhite;                                // 0x1068(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstance*                      MaterialColorBlue;                                 // 0x1070(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstance*                      MaterialColorRed;                                  // 0x1078(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               DynamicColorWhite;                                 // 0x1080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               DynamicColorBlue;                                  // 0x1088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               DynamicColorRed;                                   // 0x1090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ColorDefaultBlue;                                  // 0x1098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ColorDefaultRed;                                   // 0x10A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           LatticeUV;                                         // 0x10B8(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           AllyColor;                                         // 0x10C8(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           EnemyColor;                                        // 0x10D8(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            LightUpCurve;                                      // 0x10E8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            LightDownCurve;                                    // 0x10F0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            FadeOutCurve;                                      // 0x10F8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            ProgressLightUpCurve;                              // 0x1100(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            ProgressLightDownCurve;                            // 0x1108(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FDeclarationHolder                     ViewTargetWatcher;                                 // 0x1110(0x0010)(BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void ReceiveTick(float DeltaSeconds);
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnUpdateColor();
	void OnLegalZoneOccupied();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Level_LegalZone">();
	}
	static class APyCue_Level_LegalZone* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Level_LegalZone>();
	}
};
static_assert(alignof(APyCue_Level_LegalZone) == 0x000008, "Wrong alignment on APyCue_Level_LegalZone");
static_assert(sizeof(APyCue_Level_LegalZone) == 0x001120, "Wrong size on APyCue_Level_LegalZone");
static_assert(offsetof(APyCue_Level_LegalZone, MaterialColorWhite) == 0x001068, "Member 'APyCue_Level_LegalZone::MaterialColorWhite' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, MaterialColorBlue) == 0x001070, "Member 'APyCue_Level_LegalZone::MaterialColorBlue' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, MaterialColorRed) == 0x001078, "Member 'APyCue_Level_LegalZone::MaterialColorRed' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, DynamicColorWhite) == 0x001080, "Member 'APyCue_Level_LegalZone::DynamicColorWhite' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, DynamicColorBlue) == 0x001088, "Member 'APyCue_Level_LegalZone::DynamicColorBlue' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, DynamicColorRed) == 0x001090, "Member 'APyCue_Level_LegalZone::DynamicColorRed' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, ColorDefaultBlue) == 0x001098, "Member 'APyCue_Level_LegalZone::ColorDefaultBlue' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, ColorDefaultRed) == 0x0010A8, "Member 'APyCue_Level_LegalZone::ColorDefaultRed' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, LatticeUV) == 0x0010B8, "Member 'APyCue_Level_LegalZone::LatticeUV' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, AllyColor) == 0x0010C8, "Member 'APyCue_Level_LegalZone::AllyColor' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, EnemyColor) == 0x0010D8, "Member 'APyCue_Level_LegalZone::EnemyColor' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, LightUpCurve) == 0x0010E8, "Member 'APyCue_Level_LegalZone::LightUpCurve' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, LightDownCurve) == 0x0010F0, "Member 'APyCue_Level_LegalZone::LightDownCurve' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, FadeOutCurve) == 0x0010F8, "Member 'APyCue_Level_LegalZone::FadeOutCurve' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, ProgressLightUpCurve) == 0x001100, "Member 'APyCue_Level_LegalZone::ProgressLightUpCurve' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, ProgressLightDownCurve) == 0x001108, "Member 'APyCue_Level_LegalZone::ProgressLightDownCurve' has a wrong offset!");
static_assert(offsetof(APyCue_Level_LegalZone, ViewTargetWatcher) == 0x001110, "Member 'APyCue_Level_LegalZone::ViewTargetWatcher' has a wrong offset!");

}

