#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelPortalBase

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "MarvelLevel_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PyLevelPortalBase.PyLevelPortalBase
// 0x0080 (0x0860 - 0x07E0)
#pragma pack(push, 0x1)
class alignas(0x08) APyLevelPortalBase : public AMarvelLevelPortalBase
{
public:
	bool                                          EnablePortalTipsUI;                                // 0x07E0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7E1[0x7];                                      // 0x07E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   PortalTipsText;                                    // 0x07E8(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FUIActionData                          PressActionData;                                   // 0x0800(0x0058)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         PortalAbilityID;                                   // 0x0858(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveInit();
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelPortalBase">();
	}
	static class APyLevelPortalBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyLevelPortalBase>();
	}
};
#pragma pack(pop)
static_assert(alignof(APyLevelPortalBase) == 0x000008, "Wrong alignment on APyLevelPortalBase");
static_assert(sizeof(APyLevelPortalBase) == 0x000860, "Wrong size on APyLevelPortalBase");
static_assert(offsetof(APyLevelPortalBase, EnablePortalTipsUI) == 0x0007E0, "Member 'APyLevelPortalBase::EnablePortalTipsUI' has a wrong offset!");
static_assert(offsetof(APyLevelPortalBase, PortalTipsText) == 0x0007E8, "Member 'APyLevelPortalBase::PortalTipsText' has a wrong offset!");
static_assert(offsetof(APyLevelPortalBase, PressActionData) == 0x000800, "Member 'APyLevelPortalBase::PressActionData' has a wrong offset!");
static_assert(offsetof(APyLevelPortalBase, PortalAbilityID) == 0x000858, "Member 'APyLevelPortalBase::PortalAbilityID' has a wrong offset!");

}

