#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelController_BattlePass

#include "Basic.hpp"

#include "PyLevelController_BattlePass_classes.hpp"
#include "PyLevelController_BattlePass_parameters.hpp"


namespace SDK
{

// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnLSFadeInFinshed__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnLSFadeInFinshed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnLSFadeInFinshed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnLSCheckDetailFinished__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnLSCheckDetailFinished__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnLSCheckDetailFinished__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnLSCrystalBuyFinished__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnLSCrystalBuyFinished__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnLSCrystalBuyFinished__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnLSSettlementFinished__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnLSSettlementFinished__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnLSSettlementFinished__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnLSFadeInPlay__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnLSFadeInPlay__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnLSFadeInPlay__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnLSCheckDetailPlay__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnLSCheckDetailPlay__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnLSCheckDetailPlay__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnLSCrystalBuyPlay__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnLSCrystalBuyPlay__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnLSCrystalBuyPlay__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyLevelController_BattlePass.PyLevelController_BattlePass.OnCrystalClicked__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyLevelController_BattlePass::OnCrystalClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "OnCrystalClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// PythonFunction PyLevelController_BattlePass.PyLevelController_BattlePass.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void APyLevelController_BattlePass::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyLevelController_BattlePass.PyLevelController_BattlePass.ReceiveEndPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyLevelController_BattlePass::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelController_BattlePass", "ReceiveEndPlay");

	Params::PyLevelController_BattlePass_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

