#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelTraceMoveComponent

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyLevelTraceMoveComponent.PyLevelTraceMoveComponent
// 0x0030 (0x01E8 - 0x01B8)
class UPyLevelTraceMoveComponent final : public ULevelMoveComponent
{
public:
	float                                         CurProgress;                                       // 0x01B8(0x0004)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CurTime;                                           // 0x01BC(0x0004)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RouteIndex;                                        // 0x01C0(0x0004)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          StopMove;                                          // 0x01C4(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C5[0x3];                                      // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MoveSpeed;                                         // 0x01C8(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DefaultMove;                                       // 0x01CC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1CD[0x3];                                      // 0x01CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class AActor>                     TraceClass;                                        // 0x01D0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class ALevelMoveActor*>                OtherMoveActor;                                    // 0x01D8(0x0010)(Edit, NativeAccessSpecifierPublic)

public:
	void ReceiveInitializeComponent();
	void ReceiveBeginPlay();
	void StartMove();
	void ReverStartMove();
	void ViewportStartMove();
	void ReplaceToStart();
	void StartViewportMove();
	void StopViewportMove();
	void PyTimelineUpdate(float DeltaTime);
	void ClientSetMoveSpeed(float NewValue);
	void OnRep_CurProgress();
	void OnRep_CurTime();
	void OnRep_RouteIndex();
	void OnRep_StopMove();
	void OnRep_MoveSpeed();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelTraceMoveComponent">();
	}
	static class UPyLevelTraceMoveComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyLevelTraceMoveComponent>();
	}
};
static_assert(alignof(UPyLevelTraceMoveComponent) == 0x000008, "Wrong alignment on UPyLevelTraceMoveComponent");
static_assert(sizeof(UPyLevelTraceMoveComponent) == 0x0001E8, "Wrong size on UPyLevelTraceMoveComponent");
static_assert(offsetof(UPyLevelTraceMoveComponent, CurProgress) == 0x0001B8, "Member 'UPyLevelTraceMoveComponent::CurProgress' has a wrong offset!");
static_assert(offsetof(UPyLevelTraceMoveComponent, CurTime) == 0x0001BC, "Member 'UPyLevelTraceMoveComponent::CurTime' has a wrong offset!");
static_assert(offsetof(UPyLevelTraceMoveComponent, RouteIndex) == 0x0001C0, "Member 'UPyLevelTraceMoveComponent::RouteIndex' has a wrong offset!");
static_assert(offsetof(UPyLevelTraceMoveComponent, StopMove) == 0x0001C4, "Member 'UPyLevelTraceMoveComponent::StopMove' has a wrong offset!");
static_assert(offsetof(UPyLevelTraceMoveComponent, MoveSpeed) == 0x0001C8, "Member 'UPyLevelTraceMoveComponent::MoveSpeed' has a wrong offset!");
static_assert(offsetof(UPyLevelTraceMoveComponent, DefaultMove) == 0x0001CC, "Member 'UPyLevelTraceMoveComponent::DefaultMove' has a wrong offset!");
static_assert(offsetof(UPyLevelTraceMoveComponent, TraceClass) == 0x0001D0, "Member 'UPyLevelTraceMoveComponent::TraceClass' has a wrong offset!");
static_assert(offsetof(UPyLevelTraceMoveComponent, OtherMoveActor) == 0x0001D8, "Member 'UPyLevelTraceMoveComponent::OtherMoveActor' has a wrong offset!");

}

