#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyMRHorizationPanel

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PyMRHorizationPanel.PyMRHorizationPanel
// 0x0020 (0x0618 - 0x05F8)
class APyMRHorizationPanel final : public AMarvelLevelActorBase
{
public:
	float                                         MoveSpeed;                                         // 0x05F8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveStart;                                         // 0x05FC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveEnd;                                           // 0x0600(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NextMoveEnd;                                       // 0x0604(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 State;                                             // 0x0608(0x0010)(BlueprintVisible, Net, ZeroConstructor, RepNotify, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void SrvSetState(const class FString& State_0);
	void OnRep_State();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyMRHorizationPanel">();
	}
	static class APyMRHorizationPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyMRHorizationPanel>();
	}
};
static_assert(alignof(APyMRHorizationPanel) == 0x000008, "Wrong alignment on APyMRHorizationPanel");
static_assert(sizeof(APyMRHorizationPanel) == 0x000618, "Wrong size on APyMRHorizationPanel");
static_assert(offsetof(APyMRHorizationPanel, MoveSpeed) == 0x0005F8, "Member 'APyMRHorizationPanel::MoveSpeed' has a wrong offset!");
static_assert(offsetof(APyMRHorizationPanel, MoveStart) == 0x0005FC, "Member 'APyMRHorizationPanel::MoveStart' has a wrong offset!");
static_assert(offsetof(APyMRHorizationPanel, MoveEnd) == 0x000600, "Member 'APyMRHorizationPanel::MoveEnd' has a wrong offset!");
static_assert(offsetof(APyMRHorizationPanel, NextMoveEnd) == 0x000604, "Member 'APyMRHorizationPanel::NextMoveEnd' has a wrong offset!");
static_assert(offsetof(APyMRHorizationPanel, State) == 0x000608, "Member 'APyMRHorizationPanel::State' has a wrong offset!");

}

