#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyNoviceComputer

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyNoviceComputer.PyNoviceComputer
// 0x00B0 (0x06A8 - 0x05F8)
class APyNoviceComputer : public AMarvelLevelActorBase
{
public:
	struct FUIActionData                          HoldActionTips;                                    // 0x05F8(0x0058)(Edit, NativeAccessSpecifierPublic)
	struct FUIActionData                          PressActionTips;                                   // 0x0650(0x0058)(Edit, NativeAccessSpecifierPublic)

public:
	void ReceiveInit();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyNoviceComputer">();
	}
	static class APyNoviceComputer* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyNoviceComputer>();
	}
};
static_assert(alignof(APyNoviceComputer) == 0x000008, "Wrong alignment on APyNoviceComputer");
static_assert(sizeof(APyNoviceComputer) == 0x0006A8, "Wrong size on APyNoviceComputer");
static_assert(offsetof(APyNoviceComputer, HoldActionTips) == 0x0005F8, "Member 'APyNoviceComputer::HoldActionTips' has a wrong offset!");
static_assert(offsetof(APyNoviceComputer, PressActionTips) == 0x000650, "Member 'APyNoviceComputer::PressActionTips' has a wrong offset!");

}

