#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyNoviceBlockDoor

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyNoviceBlockDoor.PyNoviceBlockDoor
// 0x0000 (0x0608 - 0x0608)
class APyNoviceBlockDoor final : public ABirthDoor
{
public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyNoviceBlockDoor">();
	}
	static class APyNoviceBlockDoor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyNoviceBlockDoor>();
	}
};
static_assert(alignof(APyNoviceBlockDoor) == 0x000008, "Wrong alignment on APyNoviceBlockDoor");
static_assert(sizeof(APyNoviceBlockDoor) == 0x000608, "Wrong size on APyNoviceBlockDoor");

}

