#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyNoviceEscortRuleControlComponent

#include "Basic.hpp"

#include "PyNoviceRuleControlComponent_classes.hpp"


namespace SDK
{

// PythonClass PyNoviceEscortRuleControlComponent.PyNoviceEscortRuleControlComponent
// 0x0000 (0x0230 - 0x0230)
class UPyNoviceEscortRuleControlComponent final : public UPyNoviceRuleControlComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyNoviceEscortRuleControlComponent">();
	}
	static class UPyNoviceEscortRuleControlComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyNoviceEscortRuleControlComponent>();
	}
};
static_assert(alignof(UPyNoviceEscortRuleControlComponent) == 0x000008, "Wrong alignment on UPyNoviceEscortRuleControlComponent");
static_assert(sizeof(UPyNoviceEscortRuleControlComponent) == 0x000230, "Wrong size on UPyNoviceEscortRuleControlComponent");

}

