#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyNoviceTargetPracticeComputer

#include "Basic.hpp"

#include "PyNoviceTargetPracticeComputer_classes.hpp"


namespace SDK
{

// DelegateFunction PyNoviceTargetPracticeComputer.PyNoviceTargetPracticeComputer.OnPracticeFirstStart__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyNoviceTargetPracticeComputer::OnPracticeFirstStart__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyNoviceTargetPracticeComputer", "OnPracticeFirstStart__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyNoviceTargetPracticeComputer.PyNoviceTargetPracticeComputer.OnPracticeTimeOut__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyNoviceTargetPracticeComputer::OnPracticeTimeOut__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyNoviceTargetPracticeComputer", "OnPracticeTimeOut__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyNoviceTargetPracticeComputer.PyNoviceTargetPracticeComputer.OnPracticeRestart__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyNoviceTargetPracticeComputer::OnPracticeRestart__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyNoviceTargetPracticeComputer", "OnPracticeRestart__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyNoviceTargetPracticeComputer.PyNoviceTargetPracticeComputer.OnPracticeExit__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyNoviceTargetPracticeComputer::OnPracticeExit__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyNoviceTargetPracticeComputer", "OnPracticeExit__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// PythonFunction PyNoviceTargetPracticeComputer.PyNoviceTargetPracticeComputer.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void APyNoviceTargetPracticeComputer::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyNoviceTargetPracticeComputer", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

