#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyPosCreatePanel

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// PythonClass PyPosCreatePanel.PyPosCreatePanel
// 0x0060 (0x0658 - 0x05F8)
class APyPosCreatePanel final : public AMarvelLevelActorBase
{
public:
	TSubclassOf<class AActor>                     PosPoint;                                          // 0x05F8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class AActor*>                         PosPointList;                                      // 0x0600(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        PosRelativeList;                                   // 0x0610(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        PosWorldList;                                      // 0x0620(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FVector                                CenterPos;                                         // 0x0630(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WidthSpacing;                                      // 0x0648(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LengthSpacing;                                     // 0x064C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Width;                                             // 0x0650(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Length;                                            // 0x0654(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveInit();
	void PyCreatePos();
	void PyContrusction();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyPosCreatePanel">();
	}
	static class APyPosCreatePanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyPosCreatePanel>();
	}
};
static_assert(alignof(APyPosCreatePanel) == 0x000008, "Wrong alignment on APyPosCreatePanel");
static_assert(sizeof(APyPosCreatePanel) == 0x000658, "Wrong size on APyPosCreatePanel");
static_assert(offsetof(APyPosCreatePanel, PosPoint) == 0x0005F8, "Member 'APyPosCreatePanel::PosPoint' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, PosPointList) == 0x000600, "Member 'APyPosCreatePanel::PosPointList' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, PosRelativeList) == 0x000610, "Member 'APyPosCreatePanel::PosRelativeList' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, PosWorldList) == 0x000620, "Member 'APyPosCreatePanel::PosWorldList' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, CenterPos) == 0x000630, "Member 'APyPosCreatePanel::CenterPos' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, WidthSpacing) == 0x000648, "Member 'APyPosCreatePanel::WidthSpacing' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, LengthSpacing) == 0x00064C, "Member 'APyPosCreatePanel::LengthSpacing' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, Width) == 0x000650, "Member 'APyPosCreatePanel::Width' has a wrong offset!");
static_assert(offsetof(APyPosCreatePanel, Length) == 0x000654, "Member 'APyPosCreatePanel::Length' has a wrong offset!");

}

