#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyShowActorExtension_FocusGlass

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyShowActorExtension_FocusGlass.PyShowActorExtension_FocusGlass.Tick
// 0x0004 (0x0004 - 0x0000)
struct PyShowActorExtension_FocusGlass_Tick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyShowActorExtension_FocusGlass_Tick) == 0x000004, "Wrong alignment on PyShowActorExtension_FocusGlass_Tick");
static_assert(sizeof(PyShowActorExtension_FocusGlass_Tick) == 0x000004, "Wrong size on PyShowActorExtension_FocusGlass_Tick");
static_assert(offsetof(PyShowActorExtension_FocusGlass_Tick, DeltaSeconds) == 0x000000, "Member 'PyShowActorExtension_FocusGlass_Tick::DeltaSeconds' has a wrong offset!");

}

