#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyShowActorExtension_1032001

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyShowActorExtension_1032001.PyShowActorExtension_1032001.SetOriginActor
// 0x0008 (0x0008 - 0x0000)
struct PyShowActorExtension_1032001_SetOriginActor final
{
public:
	class AActor*                                 OriginActor;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyShowActorExtension_1032001_SetOriginActor) == 0x000008, "Wrong alignment on PyShowActorExtension_1032001_SetOriginActor");
static_assert(sizeof(PyShowActorExtension_1032001_SetOriginActor) == 0x000008, "Wrong size on PyShowActorExtension_1032001_SetOriginActor");
static_assert(offsetof(PyShowActorExtension_1032001_SetOriginActor, OriginActor) == 0x000000, "Member 'PyShowActorExtension_1032001_SetOriginActor::OriginActor' has a wrong offset!");

}

