#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyShowActorExtension

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "Python_enums_structs.hpp"


namespace SDK
{

// PythonClass PyShowActorExtension.PyShowActorExtension
// 0x0000 (0x0030 - 0x0030)
class UPyShowActorExtension : public UShowActorExtension
{
public:
	class AShowActorBase* GetShowActor();
	class AShowActorControl* GetShowActorControl();
	void SetOriginActor(class AActor* OriginActor);
	void BeginPlay();
	void EndPlay();
	void Tick(float DeltaSeconds);
	void SetVisible(bool Visible);
	void SetShowActorStage(EShowActorStage ShowActorStage);
	void OnIsHalfChanged(bool IsToggleHalf);
	void ResetAllMeshAnim();
	void OnPlayEmoteAnimItem(int64 ItemId);
	void On_hover_stand_finished();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyShowActorExtension">();
	}
	static class UPyShowActorExtension* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyShowActorExtension>();
	}
};
static_assert(alignof(UPyShowActorExtension) == 0x000008, "Wrong alignment on UPyShowActorExtension");
static_assert(sizeof(UPyShowActorExtension) == 0x000030, "Wrong size on UPyShowActorExtension");

}

