#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyShowActorControl

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Python_enums_structs.hpp"


namespace SDK
{

// PythonClass PyShowActorControl.PyShowActorControl
// 0x01A0 (0x0798 - 0x05F8)
class APyShowActorControl : public AShowActorControl
{
public:
	bool                                          IsDisableAllCameras;                               // 0x05F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          TurnCameraGaze;                                    // 0x05F9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UseCameraBlur;                                     // 0x05FA(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5FB[0x1];                                      // 0x05FB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CameraAperture;                                    // 0x05FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CameraFocusSmoothingInterpSpeed;                   // 0x0600(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_604[0x4];                                      // 0x0604(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CameraBlurRelativeOffset;                          // 0x0608(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ESceneCaptureCameraType                       SC_CameraType;                                     // 0x0620(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ESceneCapturePrimitiveRenderMode              SC_PrimitiveRenderMode;                            // 0x0621(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_622[0x2];                                      // 0x0622(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SC_RTSizeMultiple;                                 // 0x0624(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              SC_RtScale;                                        // 0x0628(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          SC_NeedCalculateViewportOffset;                    // 0x0638(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_639[0x3];                                      // 0x0639(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SC_MaxViewPortSize;                                // 0x063C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          SC_FixedSizeAndFov;                                // 0x0640(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          VisibleInSceneCaptureOnly;                         // 0x0641(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsAutoClearRenderTarget;                           // 0x0642(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_643[0x5];                                      // 0x0643(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextureRenderTarget*                   CachedHeroRT;                                      // 0x0648(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AutoPlayTime;                                      // 0x0650(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsAutoPlayPersonality;                             // 0x0654(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAnimationMode                                AnimationMode;                                     // 0x0655(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          LightMaskBoxOn;                                    // 0x0656(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsEnabledPhysics;                                  // 0x0657(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsAutoPlayHeroVoice;                               // 0x0658(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsEnabledPostProcess;                              // 0x0659(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_65A[0x2];                                      // 0x065A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         UVOffset;                                          // 0x065C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialParameterCollection*           MPC_Background;                                    // 0x0660(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxAnglePerSecond;                                 // 0x0668(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ActorRotationSpeed;                                // 0x066C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ActorDefaultRotationYaw;                           // 0x0670(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsAutoPlaySwitchEffect;                            // 0x0674(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsWaitExtraAssetLoaded;                            // 0x0675(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsLoadHeroGalleryAsset;                            // 0x0676(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsEnableMouseEvents;                               // 0x0677(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ExtensionID;                                       // 0x0678(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETickingGroup                                 ShowActorTickGroup;                                // 0x067C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_67D[0x3];                                      // 0x067D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CurActorClass;                                     // 0x0680(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EShowActorStage                               DefaultShowActorStage;                             // 0x0688(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EShowActorResType                             ShowActorResType;                                  // 0x0689(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_68A[0x6];                                      // 0x068A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultScene;                                      // 0x0690(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USceneComponent*                        SC_Scene;                                          // 0x0698(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USkeletalMeshComponent*                 MainMesh;                                          // 0x06A0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraComponent*                      NS_SwitchHero;                                     // 0x06A8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USceneComponent*                        CameraScene;                                       // 0x06B0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UChildActorComponent*                   SH_Stand_Camera;                                   // 0x06B8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UChildActorComponent*                   SH_Half_Camera;                                    // 0x06C0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USceneCaptureComponent2D*               SceneCapture2D;                                    // 0x06C8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPostProcessComponent*                  PostProcessComponent;                              // 0x06D0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnLoadShowActorFinish;                             // 0x06D8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnViewShowActorChanged;                            // 0x06E8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnViewShowActorVisibleChanged;                     // 0x06F8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnRotationShowActor;                               // 0x0708(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnIsHalfChanged;                                   // 0x0718(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnTextureTargetChanged;                            // 0x0728(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnPlayHoverStandFinished;                          // 0x0738(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnShowActorClicked;                                // 0x0748(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnShowActorHovered;                                // 0x0758(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnShowActorToggleHalf;                             // 0x0768(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnShowActorStageChanged;                           // 0x0778(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnPlayIdleAnim;                                    // 0x0788(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnLoadShowActorFinish__DelegateSignature(class AActor* ShowBP);
	void OnViewShowActorChanged__DelegateSignature(class AActor* ShowBP);
	void OnViewShowActorVisibleChanged__DelegateSignature(bool bVisible);
	void OnRotationShowActor__DelegateSignature(bool IsSuccess, float Angle);
	void OnIsHalfChanged__DelegateSignature(bool IsToggleHalf);
	void OnTextureTargetChanged__DelegateSignature(class UTextureRenderTarget* TextureTarget, const struct FVector2D& ViewportSize);
	void OnPlayHoverStandFinished__DelegateSignature();
	void OnShowActorClicked__DelegateSignature();
	void OnShowActorHovered__DelegateSignature(bool IsHovered);
	void OnShowActorToggleHalf__DelegateSignature(bool IsToggleHal);
	void OnShowActorStageChanged__DelegateSignature(EShowActorStage ShowActorStage);
	void OnPlayIdleAnim__DelegateSignature(bool IsPlayIdleAnim);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);
	void ShowHeroActor(int32 HeroID, int32 SkinID, int32 ShapeID);
	void LoadShowActor(const TArray<class UObject*>& Assets);
	void LoadShowActorAssetFinished(class AActor* ShowActor);
	void PlayHoverStandFinished();
	void SetIsRotationShowActor(bool IsRotationShowActor);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyShowActorControl">();
	}
	static class APyShowActorControl* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyShowActorControl>();
	}
};
static_assert(alignof(APyShowActorControl) == 0x000008, "Wrong alignment on APyShowActorControl");
static_assert(sizeof(APyShowActorControl) == 0x000798, "Wrong size on APyShowActorControl");
static_assert(offsetof(APyShowActorControl, IsDisableAllCameras) == 0x0005F8, "Member 'APyShowActorControl::IsDisableAllCameras' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, TurnCameraGaze) == 0x0005F9, "Member 'APyShowActorControl::TurnCameraGaze' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, UseCameraBlur) == 0x0005FA, "Member 'APyShowActorControl::UseCameraBlur' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, CameraAperture) == 0x0005FC, "Member 'APyShowActorControl::CameraAperture' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, CameraFocusSmoothingInterpSpeed) == 0x000600, "Member 'APyShowActorControl::CameraFocusSmoothingInterpSpeed' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, CameraBlurRelativeOffset) == 0x000608, "Member 'APyShowActorControl::CameraBlurRelativeOffset' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_CameraType) == 0x000620, "Member 'APyShowActorControl::SC_CameraType' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_PrimitiveRenderMode) == 0x000621, "Member 'APyShowActorControl::SC_PrimitiveRenderMode' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_RTSizeMultiple) == 0x000624, "Member 'APyShowActorControl::SC_RTSizeMultiple' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_RtScale) == 0x000628, "Member 'APyShowActorControl::SC_RtScale' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_NeedCalculateViewportOffset) == 0x000638, "Member 'APyShowActorControl::SC_NeedCalculateViewportOffset' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_MaxViewPortSize) == 0x00063C, "Member 'APyShowActorControl::SC_MaxViewPortSize' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_FixedSizeAndFov) == 0x000640, "Member 'APyShowActorControl::SC_FixedSizeAndFov' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, VisibleInSceneCaptureOnly) == 0x000641, "Member 'APyShowActorControl::VisibleInSceneCaptureOnly' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsAutoClearRenderTarget) == 0x000642, "Member 'APyShowActorControl::IsAutoClearRenderTarget' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, CachedHeroRT) == 0x000648, "Member 'APyShowActorControl::CachedHeroRT' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, AutoPlayTime) == 0x000650, "Member 'APyShowActorControl::AutoPlayTime' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsAutoPlayPersonality) == 0x000654, "Member 'APyShowActorControl::IsAutoPlayPersonality' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, AnimationMode) == 0x000655, "Member 'APyShowActorControl::AnimationMode' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, LightMaskBoxOn) == 0x000656, "Member 'APyShowActorControl::LightMaskBoxOn' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsEnabledPhysics) == 0x000657, "Member 'APyShowActorControl::IsEnabledPhysics' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsAutoPlayHeroVoice) == 0x000658, "Member 'APyShowActorControl::IsAutoPlayHeroVoice' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsEnabledPostProcess) == 0x000659, "Member 'APyShowActorControl::IsEnabledPostProcess' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, UVOffset) == 0x00065C, "Member 'APyShowActorControl::UVOffset' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, MPC_Background) == 0x000660, "Member 'APyShowActorControl::MPC_Background' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, MaxAnglePerSecond) == 0x000668, "Member 'APyShowActorControl::MaxAnglePerSecond' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, ActorRotationSpeed) == 0x00066C, "Member 'APyShowActorControl::ActorRotationSpeed' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, ActorDefaultRotationYaw) == 0x000670, "Member 'APyShowActorControl::ActorDefaultRotationYaw' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsAutoPlaySwitchEffect) == 0x000674, "Member 'APyShowActorControl::IsAutoPlaySwitchEffect' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsWaitExtraAssetLoaded) == 0x000675, "Member 'APyShowActorControl::IsWaitExtraAssetLoaded' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsLoadHeroGalleryAsset) == 0x000676, "Member 'APyShowActorControl::IsLoadHeroGalleryAsset' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, IsEnableMouseEvents) == 0x000677, "Member 'APyShowActorControl::IsEnableMouseEvents' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, ExtensionID) == 0x000678, "Member 'APyShowActorControl::ExtensionID' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, ShowActorTickGroup) == 0x00067C, "Member 'APyShowActorControl::ShowActorTickGroup' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, CurActorClass) == 0x000680, "Member 'APyShowActorControl::CurActorClass' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, DefaultShowActorStage) == 0x000688, "Member 'APyShowActorControl::DefaultShowActorStage' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, ShowActorResType) == 0x000689, "Member 'APyShowActorControl::ShowActorResType' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, DefaultScene) == 0x000690, "Member 'APyShowActorControl::DefaultScene' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SC_Scene) == 0x000698, "Member 'APyShowActorControl::SC_Scene' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, MainMesh) == 0x0006A0, "Member 'APyShowActorControl::MainMesh' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, NS_SwitchHero) == 0x0006A8, "Member 'APyShowActorControl::NS_SwitchHero' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, CameraScene) == 0x0006B0, "Member 'APyShowActorControl::CameraScene' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SH_Stand_Camera) == 0x0006B8, "Member 'APyShowActorControl::SH_Stand_Camera' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SH_Half_Camera) == 0x0006C0, "Member 'APyShowActorControl::SH_Half_Camera' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, SceneCapture2D) == 0x0006C8, "Member 'APyShowActorControl::SceneCapture2D' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, PostProcessComponent) == 0x0006D0, "Member 'APyShowActorControl::PostProcessComponent' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnLoadShowActorFinish) == 0x0006D8, "Member 'APyShowActorControl::OnLoadShowActorFinish' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnViewShowActorChanged) == 0x0006E8, "Member 'APyShowActorControl::OnViewShowActorChanged' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnViewShowActorVisibleChanged) == 0x0006F8, "Member 'APyShowActorControl::OnViewShowActorVisibleChanged' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnRotationShowActor) == 0x000708, "Member 'APyShowActorControl::OnRotationShowActor' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnIsHalfChanged) == 0x000718, "Member 'APyShowActorControl::OnIsHalfChanged' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnTextureTargetChanged) == 0x000728, "Member 'APyShowActorControl::OnTextureTargetChanged' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnPlayHoverStandFinished) == 0x000738, "Member 'APyShowActorControl::OnPlayHoverStandFinished' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnShowActorClicked) == 0x000748, "Member 'APyShowActorControl::OnShowActorClicked' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnShowActorHovered) == 0x000758, "Member 'APyShowActorControl::OnShowActorHovered' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnShowActorToggleHalf) == 0x000768, "Member 'APyShowActorControl::OnShowActorToggleHalf' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnShowActorStageChanged) == 0x000778, "Member 'APyShowActorControl::OnShowActorStageChanged' has a wrong offset!");
static_assert(offsetof(APyShowActorControl, OnPlayIdleAnim) == 0x000788, "Member 'APyShowActorControl::OnPlayIdleAnim' has a wrong offset!");

}

