#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PySuperFactoryEffectController

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PySuperFactoryEffectController.PySuperFactoryEffectController
// 0x0028 (0x0620 - 0x05F8)
class APySuperFactoryEffectController final : public AMarvelLevelActorBase
{
public:
	class APyControl*                             FocusControl;                                      // 0x05F8(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBattleSide                                   FocusSide;                                         // 0x0600(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_601[0x7];                                      // 0x0601(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ALevelSequenceActor*                    SeqActorOnSideWin;                                 // 0x0608(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class APostProcessVolume*>             EffectOnSideWin;                                   // 0x0610(0x0010)(Edit, NativeAccessSpecifierPublic)

public:
	void ReceiveInit();
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySuperFactoryEffectController">();
	}
	static class APySuperFactoryEffectController* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySuperFactoryEffectController>();
	}
};
static_assert(alignof(APySuperFactoryEffectController) == 0x000008, "Wrong alignment on APySuperFactoryEffectController");
static_assert(sizeof(APySuperFactoryEffectController) == 0x000620, "Wrong size on APySuperFactoryEffectController");
static_assert(offsetof(APySuperFactoryEffectController, FocusControl) == 0x0005F8, "Member 'APySuperFactoryEffectController::FocusControl' has a wrong offset!");
static_assert(offsetof(APySuperFactoryEffectController, FocusSide) == 0x000600, "Member 'APySuperFactoryEffectController::FocusSide' has a wrong offset!");
static_assert(offsetof(APySuperFactoryEffectController, SeqActorOnSideWin) == 0x000608, "Member 'APySuperFactoryEffectController::SeqActorOnSideWin' has a wrong offset!");
static_assert(offsetof(APySuperFactoryEffectController, EffectOnSideWin) == 0x000610, "Member 'APySuperFactoryEffectController::EffectOnSideWin' has a wrong offset!");

}

