#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyTokyoH01Aircraft

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass PyTokyoH01Aircraft.PyTokyoH01Aircraft
// 0x0020 (0x0648 - 0x0628)
class APyTokyoH01Aircraft final : public ALevelNPCActor
{
public:
	int32                                         ReplicateState;                                    // 0x0628(0x0004)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_62C[0x4];                                      // 0x062C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         ExplodeEffect;                                     // 0x0630(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TriggerProgress;                                   // 0x0638(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_63C[0x4];                                      // 0x063C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          ExplodeAudio;                                      // 0x0640(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveInit();
	void OnRep_ReplicateState();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTokyoH01Aircraft">();
	}
	static class APyTokyoH01Aircraft* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyTokyoH01Aircraft>();
	}
};
static_assert(alignof(APyTokyoH01Aircraft) == 0x000008, "Wrong alignment on APyTokyoH01Aircraft");
static_assert(sizeof(APyTokyoH01Aircraft) == 0x000648, "Wrong size on APyTokyoH01Aircraft");
static_assert(offsetof(APyTokyoH01Aircraft, ReplicateState) == 0x000628, "Member 'APyTokyoH01Aircraft::ReplicateState' has a wrong offset!");
static_assert(offsetof(APyTokyoH01Aircraft, ExplodeEffect) == 0x000630, "Member 'APyTokyoH01Aircraft::ExplodeEffect' has a wrong offset!");
static_assert(offsetof(APyTokyoH01Aircraft, TriggerProgress) == 0x000638, "Member 'APyTokyoH01Aircraft::TriggerProgress' has a wrong offset!");
static_assert(offsetof(APyTokyoH01Aircraft, ExplodeAudio) == 0x000640, "Member 'APyTokyoH01Aircraft::ExplodeAudio' has a wrong offset!");

// PythonClass PyTokyoH01Aircraft.PyTokyoH01AircraftAnimInstance
// 0x0010 (0x0440 - 0x0430)
class UPyTokyoH01AircraftAnimInstance final : public UAnimInstance
{
public:
	uint8                                         Pad_428[0x8];                                      // 0x0428(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bFly;                                              // 0x0430(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIdle;                                             // 0x0431(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDead;                                             // 0x0432(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTokyoH01AircraftAnimInstance">();
	}
	static class UPyTokyoH01AircraftAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyTokyoH01AircraftAnimInstance>();
	}
};
static_assert(alignof(UPyTokyoH01AircraftAnimInstance) == 0x000010, "Wrong alignment on UPyTokyoH01AircraftAnimInstance");
static_assert(sizeof(UPyTokyoH01AircraftAnimInstance) == 0x000440, "Wrong size on UPyTokyoH01AircraftAnimInstance");
static_assert(offsetof(UPyTokyoH01AircraftAnimInstance, bFly) == 0x000430, "Member 'UPyTokyoH01AircraftAnimInstance::bFly' has a wrong offset!");
static_assert(offsetof(UPyTokyoH01AircraftAnimInstance, bIdle) == 0x000431, "Member 'UPyTokyoH01AircraftAnimInstance::bIdle' has a wrong offset!");
static_assert(offsetof(UPyTokyoH01AircraftAnimInstance, bDead) == 0x000432, "Member 'UPyTokyoH01AircraftAnimInstance::bDead' has a wrong offset!");

}

