#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyUIC_SummonedHpBar

#include "Basic.hpp"

#include "PyUIC_SummonedHpBar_classes.hpp"
#include "PyUIC_SummonedHpBar_parameters.hpp"


namespace SDK
{

// PythonFunction PyUIC_SummonedHpBar.PyWidget_SummonedHpBar_Top.Construct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_SummonedHpBar_Top::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_SummonedHpBar_Top", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyUIC_SummonedHpBar.PyWidget_SummonedHpBar_Top.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_SummonedHpBar_Top::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_SummonedHpBar_Top", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyUIC_SummonedHpBar.PyWidget_SummonedHpBar_Top.SetTotalHpMax
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InTotalHpMax                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_SummonedHpBar_Top::SetTotalHpMax(float InTotalHpMax)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_SummonedHpBar_Top", "SetTotalHpMax");

	Params::PyWidget_SummonedHpBar_Top_SetTotalHpMax Parms{};

	Parms.InTotalHpMax = InTotalHpMax;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyUIC_SummonedHpBar.PyWidget_SummonedHpBar_Top.SetTotalHpCur
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InTotalHpCur                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_SummonedHpBar_Top::SetTotalHpCur(float InTotalHpCur)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_SummonedHpBar_Top", "SetTotalHpCur");

	Params::PyWidget_SummonedHpBar_Top_SetTotalHpCur Parms{};

	Parms.InTotalHpCur = InTotalHpCur;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyUIC_SummonedHpBar.PyWidget_SummonedHpBar_Top.MarvelRemoveFromParent
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_SummonedHpBar_Top::MarvelRemoveFromParent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_SummonedHpBar_Top", "MarvelRemoveFromParent");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// DelegateFunction PyUIC_SummonedHpBar.PyUIC_Summoned_HpBar.OnWidgetCreated__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void UPyUIC_Summoned_HpBar::OnWidgetCreated__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyUIC_Summoned_HpBar", "OnWidgetCreated__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// PythonFunction PyUIC_SummonedHpBar.PyUIC_Summoned_HpBar.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyUIC_Summoned_HpBar::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyUIC_Summoned_HpBar", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyUIC_SummonedHpBar.PyUIC_Summoned_HpBar.ReceiveEndPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyUIC_Summoned_HpBar::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyUIC_Summoned_HpBar", "ReceiveEndPlay");

	Params::PyUIC_Summoned_HpBar_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyUIC_SummonedHpBar.PyUIC_Summoned_HpBar.OnOwnerInstigatorTagChanged
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FGameplayTag                     Tag                                                    (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// bool                                    bTagExists                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyUIC_Summoned_HpBar::OnOwnerInstigatorTagChanged(const struct FGameplayTag& Tag, bool bTagExists)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyUIC_Summoned_HpBar", "OnOwnerInstigatorTagChanged");

	Params::PyUIC_Summoned_HpBar_OnOwnerInstigatorTagChanged Parms{};

	Parms.Tag = std::move(Tag);
	Parms.bTagExists = bTagExists;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

