#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyUpdraftRange

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyUpdraftRange.PyUpdraftRange
// 0x0008 (0x0680 - 0x0678)
class APyUpdraftRange final : public AUpdraftRange
{
public:
	float                                         VelocityZ;                                         // 0x0678(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void Update();
	void OnCharacterEnterRange(class AMarvelBaseCharacter* Character);
	void OnCharacterExitRange(class AMarvelBaseCharacter* Character);

	EControlPointType GetType() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUpdraftRange">();
	}
	static class APyUpdraftRange* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyUpdraftRange>();
	}
};
static_assert(alignof(APyUpdraftRange) == 0x000008, "Wrong alignment on APyUpdraftRange");
static_assert(sizeof(APyUpdraftRange) == 0x000680, "Wrong size on APyUpdraftRange");
static_assert(offsetof(APyUpdraftRange, VelocityZ) == 0x000678, "Member 'APyUpdraftRange::VelocityZ' has a wrong offset!");

}

