#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyVibraniumWithShake

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyVibraniumWithShake.PyVibraniumWithShake.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyVibraniumWithShake_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndReason;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyVibraniumWithShake_ReceiveEndPlay) == 0x000001, "Wrong alignment on PyVibraniumWithShake_ReceiveEndPlay");
static_assert(sizeof(PyVibraniumWithShake_ReceiveEndPlay) == 0x000001, "Wrong size on PyVibraniumWithShake_ReceiveEndPlay");
static_assert(offsetof(PyVibraniumWithShake_ReceiveEndPlay, EndReason) == 0x000000, "Member 'PyVibraniumWithShake_ReceiveEndPlay::EndReason' has a wrong offset!");

}

