#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Secondary_QuestionFeedback

#include "Basic.hpp"

#include "PyWidget_SecondaryChildBase_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_QuestionFeedback.PyWidget_Secondary_QuestionFeedbackProcess
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Secondary_QuestionFeedbackProcess final : public UPyWidget_SecondaryChildBase
{
public:
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_QuestionFeedbackProcess">();
	}
	static class UPyWidget_Secondary_QuestionFeedbackProcess* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_QuestionFeedbackProcess>();
	}
};
static_assert(alignof(UPyWidget_Secondary_QuestionFeedbackProcess) == 0x000008, "Wrong alignment on UPyWidget_Secondary_QuestionFeedbackProcess");
static_assert(sizeof(UPyWidget_Secondary_QuestionFeedbackProcess) == 0x0005E8, "Wrong size on UPyWidget_Secondary_QuestionFeedbackProcess");

// PythonClass PyWidget_Secondary_QuestionFeedback.PyWidget_Secondary_QuestionFeedback
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Secondary_QuestionFeedback final : public UPyWidget_SecondaryChildBase
{
public:
	void OnInitialized();
	class UWidget* NavigateToCheckBox0(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox1(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox2(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox3(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox4(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox5(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox6(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox7(EUINavigation Navigation_0);
	class UWidget* NavigateToCheckBox8(EUINavigation Navigation_0);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_QuestionFeedback">();
	}
	static class UPyWidget_Secondary_QuestionFeedback* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_QuestionFeedback>();
	}
};
static_assert(alignof(UPyWidget_Secondary_QuestionFeedback) == 0x000008, "Wrong alignment on UPyWidget_Secondary_QuestionFeedback");
static_assert(sizeof(UPyWidget_Secondary_QuestionFeedback) == 0x0005E8, "Wrong size on UPyWidget_Secondary_QuestionFeedback");

}

