#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_BreakIce_AwardList

#include "Basic.hpp"


namespace SDK::Params
{

// DelegateFunction PyWidget_BreakIce_AwardList.PyWidget_BreakIce_AwardList.OnItemClicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_BreakIce_AwardList_OnItemClicked__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_BreakIce_AwardList_OnItemClicked__DelegateSignature) == 0x000004, "Wrong alignment on PyWidget_BreakIce_AwardList_OnItemClicked__DelegateSignature");
static_assert(sizeof(PyWidget_BreakIce_AwardList_OnItemClicked__DelegateSignature) == 0x000004, "Wrong size on PyWidget_BreakIce_AwardList_OnItemClicked__DelegateSignature");
static_assert(offsetof(PyWidget_BreakIce_AwardList_OnItemClicked__DelegateSignature, Index_0) == 0x000000, "Member 'PyWidget_BreakIce_AwardList_OnItemClicked__DelegateSignature::Index_0' has a wrong offset!");

}

