#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Secondary_RoomSetting

#include "Basic.hpp"

#include "PyWidget_SecondaryChildBase_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_RoomSetting.PyWidgetSecondaryRoomSetting
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidgetSecondaryRoomSetting final : public UPyWidget_SecondaryChildBase
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);
	class UWidget* btn_navigation_rule_custom(EUINavigation NavType);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidgetSecondaryRoomSetting">();
	}
	static class UPyWidgetSecondaryRoomSetting* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidgetSecondaryRoomSetting>();
	}
};
static_assert(alignof(UPyWidgetSecondaryRoomSetting) == 0x000008, "Wrong alignment on UPyWidgetSecondaryRoomSetting");
static_assert(sizeof(UPyWidgetSecondaryRoomSetting) == 0x0005E8, "Wrong size on UPyWidgetSecondaryRoomSetting");

}

