#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Replay_ProcessBar

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_Replay_ProcessBar.PyWidget_Replay_ProcessBar
// 0x0038 (0x0620 - 0x05E8)
class UPyWidget_Replay_ProcessBar final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UTexture2D*>                     MapEventIconList;                                  // 0x05E8(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_ProcessChange;                             // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                ReplayButtonClass;                                 // 0x0600(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                ReplayKillinfoClass;                               // 0x0608(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                ReplayKillinfoUnitClass;                           // 0x0610(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                ReplayRoundResultInfoClass;                        // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Replay_ProcessBar">();
	}
	static class UPyWidget_Replay_ProcessBar* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Replay_ProcessBar>();
	}
};
static_assert(alignof(UPyWidget_Replay_ProcessBar) == 0x000008, "Wrong alignment on UPyWidget_Replay_ProcessBar");
static_assert(sizeof(UPyWidget_Replay_ProcessBar) == 0x000620, "Wrong size on UPyWidget_Replay_ProcessBar");
static_assert(offsetof(UPyWidget_Replay_ProcessBar, MapEventIconList) == 0x0005E8, "Member 'UPyWidget_Replay_ProcessBar::MapEventIconList' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_ProcessBar, AkEvent_ProcessChange) == 0x0005F8, "Member 'UPyWidget_Replay_ProcessBar::AkEvent_ProcessChange' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_ProcessBar, ReplayButtonClass) == 0x000600, "Member 'UPyWidget_Replay_ProcessBar::ReplayButtonClass' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_ProcessBar, ReplayKillinfoClass) == 0x000608, "Member 'UPyWidget_Replay_ProcessBar::ReplayKillinfoClass' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_ProcessBar, ReplayKillinfoUnitClass) == 0x000610, "Member 'UPyWidget_Replay_ProcessBar::ReplayKillinfoUnitClass' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_ProcessBar, ReplayRoundResultInfoClass) == 0x000618, "Member 'UPyWidget_Replay_ProcessBar::ReplayRoundResultInfoClass' has a wrong offset!");

// PythonClass PyWidget_Replay_ProcessBar.PyWidget_Replay_SingleProcessBar
// 0x0108 (0x06F0 - 0x05E8)
class UPyWidget_Replay_SingleProcessBar final : public UPyMarvelUserWidget
{
public:
	bool                                          bIsAlly;                                           // 0x05E2(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5E3[0x1];                                      // 0x05E3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           BackboardColor;                                    // 0x05E4(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           PreloadColor;                                      // 0x05F4(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ProgressColor;                                     // 0x0604(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_614[0xC];                                      // 0x0614(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            PreloadBrush;                                      // 0x0620(0x00D0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void PreConstruct(bool IsDesignTime);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Replay_SingleProcessBar">();
	}
	static class UPyWidget_Replay_SingleProcessBar* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Replay_SingleProcessBar>();
	}
};
static_assert(alignof(UPyWidget_Replay_SingleProcessBar) == 0x000010, "Wrong alignment on UPyWidget_Replay_SingleProcessBar");
static_assert(sizeof(UPyWidget_Replay_SingleProcessBar) == 0x0006F0, "Wrong size on UPyWidget_Replay_SingleProcessBar");
static_assert(offsetof(UPyWidget_Replay_SingleProcessBar, bIsAlly) == 0x0005E2, "Member 'UPyWidget_Replay_SingleProcessBar::bIsAlly' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_SingleProcessBar, BackboardColor) == 0x0005E4, "Member 'UPyWidget_Replay_SingleProcessBar::BackboardColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_SingleProcessBar, PreloadColor) == 0x0005F4, "Member 'UPyWidget_Replay_SingleProcessBar::PreloadColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_SingleProcessBar, ProgressColor) == 0x000604, "Member 'UPyWidget_Replay_SingleProcessBar::ProgressColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Replay_SingleProcessBar, PreloadBrush) == 0x000620, "Member 'UPyWidget_Replay_SingleProcessBar::PreloadBrush' has a wrong offset!");

}

