#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Career_HonorBadge

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Career_HonorBadge.PyWidget_Career_HonorBadge
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Career_HonorBadge final : public UPyMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Career_HonorBadge">();
	}
	static class UPyWidget_Career_HonorBadge* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Career_HonorBadge>();
	}
};
static_assert(alignof(UPyWidget_Career_HonorBadge) == 0x000008, "Wrong alignment on UPyWidget_Career_HonorBadge");
static_assert(sizeof(UPyWidget_Career_HonorBadge) == 0x0005E8, "Wrong size on UPyWidget_Career_HonorBadge");

}

