#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Control_Rounds

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Control_Rounds.PyWidget_Control_Rounds
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Control_Rounds final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Control_Rounds">();
	}
	static class UPyWidget_Control_Rounds* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Control_Rounds>();
	}
};
static_assert(alignof(UPyWidget_Control_Rounds) == 0x000008, "Wrong alignment on UPyWidget_Control_Rounds");
static_assert(sizeof(UPyWidget_Control_Rounds) == 0x0005E8, "Wrong size on UPyWidget_Control_Rounds");

}

