#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_BondDemandHeroesTips

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_BondDemandHeroesTips.PyWidget_BondDemandHeroesTips
// 0x0038 (0x0620 - 0x05E8)
class UPyWidget_BondDemandHeroesTips : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x2];                                      // 0x05E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ShowTime;                                          // 0x05E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          ShowAudio;                                         // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             ImgIconBan;                                        // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             ImgIconPick;                                       // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           DefaultColor;                                      // 0x0600(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           BanColor;                                          // 0x0610(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BondDemandHeroesTips">();
	}
	static class UPyWidget_BondDemandHeroesTips* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BondDemandHeroesTips>();
	}
};
static_assert(alignof(UPyWidget_BondDemandHeroesTips) == 0x000008, "Wrong alignment on UPyWidget_BondDemandHeroesTips");
static_assert(sizeof(UPyWidget_BondDemandHeroesTips) == 0x000620, "Wrong size on UPyWidget_BondDemandHeroesTips");
static_assert(offsetof(UPyWidget_BondDemandHeroesTips, ShowTime) == 0x0005E4, "Member 'UPyWidget_BondDemandHeroesTips::ShowTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_BondDemandHeroesTips, ShowAudio) == 0x0005E8, "Member 'UPyWidget_BondDemandHeroesTips::ShowAudio' has a wrong offset!");
static_assert(offsetof(UPyWidget_BondDemandHeroesTips, ImgIconBan) == 0x0005F0, "Member 'UPyWidget_BondDemandHeroesTips::ImgIconBan' has a wrong offset!");
static_assert(offsetof(UPyWidget_BondDemandHeroesTips, ImgIconPick) == 0x0005F8, "Member 'UPyWidget_BondDemandHeroesTips::ImgIconPick' has a wrong offset!");
static_assert(offsetof(UPyWidget_BondDemandHeroesTips, DefaultColor) == 0x000600, "Member 'UPyWidget_BondDemandHeroesTips::DefaultColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_BondDemandHeroesTips, BanColor) == 0x000610, "Member 'UPyWidget_BondDemandHeroesTips::BanColor' has a wrong offset!");

// PythonClass PyWidget_BondDemandHeroesTips.PyWidget_BondDemandHeroHead
// 0x0018 (0x0600 - 0x05E8)
class UPyWidget_BondDemandHeroHead : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             TankIcon;                                          // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             DamageIcon;                                        // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             SupportIcon;                                       // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BondDemandHeroHead">();
	}
	static class UPyWidget_BondDemandHeroHead* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BondDemandHeroHead>();
	}
};
static_assert(alignof(UPyWidget_BondDemandHeroHead) == 0x000008, "Wrong alignment on UPyWidget_BondDemandHeroHead");
static_assert(sizeof(UPyWidget_BondDemandHeroHead) == 0x000600, "Wrong size on UPyWidget_BondDemandHeroHead");
static_assert(offsetof(UPyWidget_BondDemandHeroHead, TankIcon) == 0x0005E8, "Member 'UPyWidget_BondDemandHeroHead::TankIcon' has a wrong offset!");
static_assert(offsetof(UPyWidget_BondDemandHeroHead, DamageIcon) == 0x0005F0, "Member 'UPyWidget_BondDemandHeroHead::DamageIcon' has a wrong offset!");
static_assert(offsetof(UPyWidget_BondDemandHeroHead, SupportIcon) == 0x0005F8, "Member 'UPyWidget_BondDemandHeroHead::SupportIcon' has a wrong offset!");

}

