#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_BattlePass_Settlement

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_BattlePass_Settlement.PyWidget_Secondary_BattlePass_Settlement.on_try_srcoll_when_next_focusable_child_change
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change final
{
public:
	int32                                         ChildIndex;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         FocusedChildDirection;                             // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumItemsLine;                                      // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UButton*                                ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change) == 0x000008, "Wrong alignment on PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change");
static_assert(sizeof(PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change) == 0x000018, "Wrong size on PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change");
static_assert(offsetof(PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change, ChildIndex) == 0x000000, "Member 'PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change::ChildIndex' has a wrong offset!");
static_assert(offsetof(PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change, FocusedChildDirection) == 0x000004, "Member 'PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change::FocusedChildDirection' has a wrong offset!");
static_assert(offsetof(PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change, NumItemsLine) == 0x000008, "Member 'PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change::NumItemsLine' has a wrong offset!");
static_assert(offsetof(PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change, ReturnValue) == 0x000010, "Member 'PyWidget_Secondary_BattlePass_Settlement_On_try_srcoll_when_next_focusable_child_change::ReturnValue' has a wrong offset!");

// PythonFunction PyWidget_BattlePass_Settlement.PyWidget_BattlePass_Settlement.OnVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_BattlePass_Settlement_OnVisibleChanged final
{
public:
	bool                                          bNewVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_BattlePass_Settlement_OnVisibleChanged) == 0x000001, "Wrong alignment on PyWidget_BattlePass_Settlement_OnVisibleChanged");
static_assert(sizeof(PyWidget_BattlePass_Settlement_OnVisibleChanged) == 0x000001, "Wrong size on PyWidget_BattlePass_Settlement_OnVisibleChanged");
static_assert(offsetof(PyWidget_BattlePass_Settlement_OnVisibleChanged, bNewVisible) == 0x000000, "Member 'PyWidget_BattlePass_Settlement_OnVisibleChanged::bNewVisible' has a wrong offset!");

}

