#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Secondary_ClanNotification

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"
#include "PyWidget_SecondaryChildBase_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_ClanNotification.PyWidget_Secondary_ClanNotification
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Secondary_ClanNotification final : public UPyWidget_SecondaryChildBase
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_ClanNotification">();
	}
	static class UPyWidget_Secondary_ClanNotification* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_ClanNotification>();
	}
};
static_assert(alignof(UPyWidget_Secondary_ClanNotification) == 0x000008, "Wrong alignment on UPyWidget_Secondary_ClanNotification");
static_assert(sizeof(UPyWidget_Secondary_ClanNotification) == 0x0005E8, "Wrong size on UPyWidget_Secondary_ClanNotification");

// PythonClass PyWidget_Secondary_ClanNotification.PyWidget_ClanNotificationBtn
// 0x0050 (0x0638 - 0x05E8)
class UPyWidget_ClanNotificationBtn final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   BtnText;                                           // 0x05E8(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FSlateColor                            NormalColor;                                       // 0x0600(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            SelectedColor;                                     // 0x0614(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	FMulticastInlineDelegateProperty_             OnClicked;                                         // 0x0628(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnClicked__DelegateSignature();
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_ClanNotificationBtn">();
	}
	static class UPyWidget_ClanNotificationBtn* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_ClanNotificationBtn>();
	}
};
static_assert(alignof(UPyWidget_ClanNotificationBtn) == 0x000008, "Wrong alignment on UPyWidget_ClanNotificationBtn");
static_assert(sizeof(UPyWidget_ClanNotificationBtn) == 0x000638, "Wrong size on UPyWidget_ClanNotificationBtn");
static_assert(offsetof(UPyWidget_ClanNotificationBtn, BtnText) == 0x0005E8, "Member 'UPyWidget_ClanNotificationBtn::BtnText' has a wrong offset!");
static_assert(offsetof(UPyWidget_ClanNotificationBtn, NormalColor) == 0x000600, "Member 'UPyWidget_ClanNotificationBtn::NormalColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_ClanNotificationBtn, SelectedColor) == 0x000614, "Member 'UPyWidget_ClanNotificationBtn::SelectedColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_ClanNotificationBtn, OnClicked) == 0x000628, "Member 'UPyWidget_ClanNotificationBtn::OnClicked' has a wrong offset!");

}

