#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Secondary_Reward

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_Reward.PyWidget_Secondary_Reward
// 0x0030 (0x0618 - 0x05E8)
class UPyWidget_Secondary_Reward final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UPyWidget_Secondary_PopupUnit> MallItemBox;                                       // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMargin                                ItemPadding;                                       // 0x05F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FMargin                                HorBoxPadding;                                     // 0x0600(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_ShowAward;                                 // 0x0610(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_Reward">();
	}
	static class UPyWidget_Secondary_Reward* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_Reward>();
	}
};
static_assert(alignof(UPyWidget_Secondary_Reward) == 0x000008, "Wrong alignment on UPyWidget_Secondary_Reward");
static_assert(sizeof(UPyWidget_Secondary_Reward) == 0x000618, "Wrong size on UPyWidget_Secondary_Reward");
static_assert(offsetof(UPyWidget_Secondary_Reward, MallItemBox) == 0x0005E8, "Member 'UPyWidget_Secondary_Reward::MallItemBox' has a wrong offset!");
static_assert(offsetof(UPyWidget_Secondary_Reward, ItemPadding) == 0x0005F0, "Member 'UPyWidget_Secondary_Reward::ItemPadding' has a wrong offset!");
static_assert(offsetof(UPyWidget_Secondary_Reward, HorBoxPadding) == 0x000600, "Member 'UPyWidget_Secondary_Reward::HorBoxPadding' has a wrong offset!");
static_assert(offsetof(UPyWidget_Secondary_Reward, AkEvent_ShowAward) == 0x000610, "Member 'UPyWidget_Secondary_Reward::AkEvent_ShowAward' has a wrong offset!");

}

