#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_ReplaySelectHeroPanel

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_ReplaySelectHeroPanel.PyWidget_ReplaySelectHeroPanel
// 0x0058 (0x0640 - 0x05E8)
class UPyWidget_ReplaySelectHeroPanel final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UUserWidget>                BondIconClass;                                     // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             ImgIconBan;                                        // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             ImgIconPick;                                       // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           BanColor;                                          // 0x0600(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           PickColor;                                         // 0x0610(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           SelectColor;                                       // 0x0620(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           DefalutColor;                                      // 0x0630(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);
	void MarvelSetVisibleImmediately(bool Visible);
	void OnCascadingVisibleChanged(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_ReplaySelectHeroPanel">();
	}
	static class UPyWidget_ReplaySelectHeroPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_ReplaySelectHeroPanel>();
	}
};
static_assert(alignof(UPyWidget_ReplaySelectHeroPanel) == 0x000008, "Wrong alignment on UPyWidget_ReplaySelectHeroPanel");
static_assert(sizeof(UPyWidget_ReplaySelectHeroPanel) == 0x000640, "Wrong size on UPyWidget_ReplaySelectHeroPanel");
static_assert(offsetof(UPyWidget_ReplaySelectHeroPanel, BondIconClass) == 0x0005E8, "Member 'UPyWidget_ReplaySelectHeroPanel::BondIconClass' has a wrong offset!");
static_assert(offsetof(UPyWidget_ReplaySelectHeroPanel, ImgIconBan) == 0x0005F0, "Member 'UPyWidget_ReplaySelectHeroPanel::ImgIconBan' has a wrong offset!");
static_assert(offsetof(UPyWidget_ReplaySelectHeroPanel, ImgIconPick) == 0x0005F8, "Member 'UPyWidget_ReplaySelectHeroPanel::ImgIconPick' has a wrong offset!");
static_assert(offsetof(UPyWidget_ReplaySelectHeroPanel, BanColor) == 0x000600, "Member 'UPyWidget_ReplaySelectHeroPanel::BanColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_ReplaySelectHeroPanel, PickColor) == 0x000610, "Member 'UPyWidget_ReplaySelectHeroPanel::PickColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_ReplaySelectHeroPanel, SelectColor) == 0x000620, "Member 'UPyWidget_ReplaySelectHeroPanel::SelectColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_ReplaySelectHeroPanel, DefalutColor) == 0x000630, "Member 'UPyWidget_ReplaySelectHeroPanel::DefalutColor' has a wrong offset!");

}

