#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_BattlePass_RuleContainer

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_BattlePass_RuleContainer.PyWidget_BattlePass_RuleContainer
// 0x0008 (0x0618 - 0x0610)
class UPyWidget_BattlePass_RuleContainer final : public UPyWidget_ModuleMainPanel
{
public:
	uint8                                         Pad_609[0x7];                                      // 0x0609(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMarvelCanvasPanel*                     CanvasPanel_Main;                                  // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_BattlePass_RuleContainer">();
	}
	static class UPyWidget_BattlePass_RuleContainer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BattlePass_RuleContainer>();
	}
};
static_assert(alignof(UPyWidget_BattlePass_RuleContainer) == 0x000008, "Wrong alignment on UPyWidget_BattlePass_RuleContainer");
static_assert(sizeof(UPyWidget_BattlePass_RuleContainer) == 0x000618, "Wrong size on UPyWidget_BattlePass_RuleContainer");
static_assert(offsetof(UPyWidget_BattlePass_RuleContainer, CanvasPanel_Main) == 0x000610, "Member 'UPyWidget_BattlePass_RuleContainer::CanvasPanel_Main' has a wrong offset!");

}

