#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Secondary_CustomLeagueRenamePanel

#include "Basic.hpp"

#include "PyWidget_SecondaryChildBase_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_CustomLeagueRenamePanel.PyWidget_Secondary_CustomLeagueRenamePanel
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Secondary_CustomLeagueRenamePanel final : public UPyWidget_SecondaryChildBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_CustomLeagueRenamePanel">();
	}
	static class UPyWidget_Secondary_CustomLeagueRenamePanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_CustomLeagueRenamePanel>();
	}
};
static_assert(alignof(UPyWidget_Secondary_CustomLeagueRenamePanel) == 0x000008, "Wrong alignment on UPyWidget_Secondary_CustomLeagueRenamePanel");
static_assert(sizeof(UPyWidget_Secondary_CustomLeagueRenamePanel) == 0x0005E8, "Wrong size on UPyWidget_Secondary_CustomLeagueRenamePanel");

}

