#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_SpringFestivalMain

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_SpringFestivalMain.PyWidget_SpringFestivalMain
// 0x0058 (0x0640 - 0x05E8)
class UPyWidget_SpringFestivalMain final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetStyle_BattlePersistentTip       ForbidHoldTheBallTip;                              // 0x05E8(0x0048)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         CountdownEmphasizeVxTime;                          // 0x0630(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_634[0x4];                                      // 0x0634(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Texture_Tackle;                                    // 0x0638(0x0008)(Edit, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_SpringFestivalMain">();
	}
	static class UPyWidget_SpringFestivalMain* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_SpringFestivalMain>();
	}
};
static_assert(alignof(UPyWidget_SpringFestivalMain) == 0x000008, "Wrong alignment on UPyWidget_SpringFestivalMain");
static_assert(sizeof(UPyWidget_SpringFestivalMain) == 0x000640, "Wrong size on UPyWidget_SpringFestivalMain");
static_assert(offsetof(UPyWidget_SpringFestivalMain, ForbidHoldTheBallTip) == 0x0005E8, "Member 'UPyWidget_SpringFestivalMain::ForbidHoldTheBallTip' has a wrong offset!");
static_assert(offsetof(UPyWidget_SpringFestivalMain, CountdownEmphasizeVxTime) == 0x000630, "Member 'UPyWidget_SpringFestivalMain::CountdownEmphasizeVxTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_SpringFestivalMain, Texture_Tackle) == 0x000638, "Member 'UPyWidget_SpringFestivalMain::Texture_Tackle' has a wrong offset!");

}

