#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_League_ScheduleOverview_EventInformation

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_League_ScheduleOverview_EventInformation.PyWidget_League_ScheduleOverview_EventInformation
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_League_ScheduleOverview_EventInformation final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_League_ScheduleOverview_EventInformation">();
	}
	static class UPyWidget_League_ScheduleOverview_EventInformation* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_League_ScheduleOverview_EventInformation>();
	}
};
static_assert(alignof(UPyWidget_League_ScheduleOverview_EventInformation) == 0x000008, "Wrong alignment on UPyWidget_League_ScheduleOverview_EventInformation");
static_assert(sizeof(UPyWidget_League_ScheduleOverview_EventInformation) == 0x0005E8, "Wrong size on UPyWidget_League_ScheduleOverview_EventInformation");

// PythonClass PyWidget_League_ScheduleOverview_EventInformation.WBP_League_ScheduleOverview_EventInformation_Item
// 0x0008 (0x05F0 - 0x05E8)
class UWBP_League_ScheduleOverview_EventInformation_Item final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Icon_Tex;                                          // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WBP_League_ScheduleOverview_EventInformation_Item">();
	}
	static class UWBP_League_ScheduleOverview_EventInformation_Item* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_League_ScheduleOverview_EventInformation_Item>();
	}
};
static_assert(alignof(UWBP_League_ScheduleOverview_EventInformation_Item) == 0x000008, "Wrong alignment on UWBP_League_ScheduleOverview_EventInformation_Item");
static_assert(sizeof(UWBP_League_ScheduleOverview_EventInformation_Item) == 0x0005F0, "Wrong size on UWBP_League_ScheduleOverview_EventInformation_Item");
static_assert(offsetof(UWBP_League_ScheduleOverview_EventInformation_Item, Icon_Tex) == 0x0005E8, "Member 'UWBP_League_ScheduleOverview_EventInformation_Item::Icon_Tex' has a wrong offset!");

}

