#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity122_HeroDetailEntry

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Activity122_HeroDetailEntry.PyWidget_Activity122_HeroDetailEntry.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Activity122_HeroDetailEntry_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_Activity122_HeroDetailEntry_PreConstruct) == 0x000001, "Wrong alignment on PyWidget_Activity122_HeroDetailEntry_PreConstruct");
static_assert(sizeof(PyWidget_Activity122_HeroDetailEntry_PreConstruct) == 0x000001, "Wrong size on PyWidget_Activity122_HeroDetailEntry_PreConstruct");
static_assert(offsetof(PyWidget_Activity122_HeroDetailEntry_PreConstruct, IsDesignTime) == 0x000000, "Member 'PyWidget_Activity122_HeroDetailEntry_PreConstruct::IsDesignTime' has a wrong offset!");

// PythonFunction PyWidget_Activity122_HeroDetailEntry.PyWidget_Activity122_HeroDetailEntry.SetAnimationStart
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_Activity122_HeroDetailEntry_SetAnimationStart final
{
public:
	float                                         Time;                                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_Activity122_HeroDetailEntry_SetAnimationStart) == 0x000004, "Wrong alignment on PyWidget_Activity122_HeroDetailEntry_SetAnimationStart");
static_assert(sizeof(PyWidget_Activity122_HeroDetailEntry_SetAnimationStart) == 0x000004, "Wrong size on PyWidget_Activity122_HeroDetailEntry_SetAnimationStart");
static_assert(offsetof(PyWidget_Activity122_HeroDetailEntry_SetAnimationStart, Time) == 0x000000, "Member 'PyWidget_Activity122_HeroDetailEntry_SetAnimationStart::Time' has a wrong offset!");

}

