#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_PopupAd_Base

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_PopupAd_Base.PyWidget_PopupAd_Base.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_PopupAd_Base_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_PopupAd_Base_MarvelSetVisible) == 0x000001, "Wrong alignment on PyWidget_PopupAd_Base_MarvelSetVisible");
static_assert(sizeof(PyWidget_PopupAd_Base_MarvelSetVisible) == 0x000001, "Wrong size on PyWidget_PopupAd_Base_MarvelSetVisible");
static_assert(offsetof(PyWidget_PopupAd_Base_MarvelSetVisible, Visible) == 0x000000, "Member 'PyWidget_PopupAd_Base_MarvelSetVisible::Visible' has a wrong offset!");

}

