#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Secondary_InviteCode

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Secondary_InviteCode.PyWidget_Secondary_InviteCode
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Secondary_InviteCode final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnHovered_0();
	void OnUnhovered_0();
	void OnHovered_1();
	void OnUnhovered_1();
	void OnHovered_2();
	void OnUnhovered_2();
	void OnHovered_3();
	void OnUnhovered_3();
	void OnHovered_4();
	void OnUnhovered_4();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Secondary_InviteCode">();
	}
	static class UPyWidget_Secondary_InviteCode* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Secondary_InviteCode>();
	}
};
static_assert(alignof(UPyWidget_Secondary_InviteCode) == 0x000008, "Wrong alignment on UPyWidget_Secondary_InviteCode");
static_assert(sizeof(UPyWidget_Secondary_InviteCode) == 0x0005E8, "Wrong size on UPyWidget_Secondary_InviteCode");

}

