#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Loading_Lobby

#include "Basic.hpp"

#include "PyWidget_Loading_Base_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Loading_Lobby.PyWidget_Loading_Lobby
// 0x0008 (0x0618 - 0x0610)
class UPyWidget_Loading_Lobby final : public UPyWidget_Loading_Base
{
public:
	uint8                                         Pad_609[0x7];                                      // 0x0609(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPyWidget_Loading_Icon*                 WBP_Loading_Icon;                                  // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Loading_Lobby">();
	}
	static class UPyWidget_Loading_Lobby* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Loading_Lobby>();
	}
};
static_assert(alignof(UPyWidget_Loading_Lobby) == 0x000008, "Wrong alignment on UPyWidget_Loading_Lobby");
static_assert(sizeof(UPyWidget_Loading_Lobby) == 0x000618, "Wrong size on UPyWidget_Loading_Lobby");
static_assert(offsetof(UPyWidget_Loading_Lobby, WBP_Loading_Icon) == 0x000610, "Member 'UPyWidget_Loading_Lobby::WBP_Loading_Icon' has a wrong offset!");

}

