#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Settlement_HighLight

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Settlement_HighLight.PyWidget_HighLight_InGamePanel.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_HighLight_InGamePanel_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_HighLight_InGamePanel_MarvelSetVisible) == 0x000001, "Wrong alignment on PyWidget_HighLight_InGamePanel_MarvelSetVisible");
static_assert(sizeof(PyWidget_HighLight_InGamePanel_MarvelSetVisible) == 0x000001, "Wrong size on PyWidget_HighLight_InGamePanel_MarvelSetVisible");
static_assert(offsetof(PyWidget_HighLight_InGamePanel_MarvelSetVisible, Visible) == 0x000000, "Member 'PyWidget_HighLight_InGamePanel_MarvelSetVisible::Visible' has a wrong offset!");

}

