#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_SpringFestival_Task_Center

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_SpringFestival_Task_Center.PyWidget_SpringFestival_Task_Center
// 0x0050 (0x0638 - 0x05E8)
class UPyWidget_SpringFestival_Task_Center final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x2];                                      // 0x05E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ShowTime;                                          // 0x05E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            OwnCenterColorLight;                               // 0x05E8(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            EnemyCenterColorLight;                             // 0x05FC(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            OwnCenterColorDark;                                // 0x0610(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            EnemyCenterColorDark;                              // 0x0624(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_SpringFestival_Task_Center">();
	}
	static class UPyWidget_SpringFestival_Task_Center* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_SpringFestival_Task_Center>();
	}
};
static_assert(alignof(UPyWidget_SpringFestival_Task_Center) == 0x000008, "Wrong alignment on UPyWidget_SpringFestival_Task_Center");
static_assert(sizeof(UPyWidget_SpringFestival_Task_Center) == 0x000638, "Wrong size on UPyWidget_SpringFestival_Task_Center");
static_assert(offsetof(UPyWidget_SpringFestival_Task_Center, ShowTime) == 0x0005E4, "Member 'UPyWidget_SpringFestival_Task_Center::ShowTime' has a wrong offset!");
static_assert(offsetof(UPyWidget_SpringFestival_Task_Center, OwnCenterColorLight) == 0x0005E8, "Member 'UPyWidget_SpringFestival_Task_Center::OwnCenterColorLight' has a wrong offset!");
static_assert(offsetof(UPyWidget_SpringFestival_Task_Center, EnemyCenterColorLight) == 0x0005FC, "Member 'UPyWidget_SpringFestival_Task_Center::EnemyCenterColorLight' has a wrong offset!");
static_assert(offsetof(UPyWidget_SpringFestival_Task_Center, OwnCenterColorDark) == 0x000610, "Member 'UPyWidget_SpringFestival_Task_Center::OwnCenterColorDark' has a wrong offset!");
static_assert(offsetof(UPyWidget_SpringFestival_Task_Center, EnemyCenterColorDark) == 0x000624, "Member 'UPyWidget_SpringFestival_Task_Center::EnemyCenterColorDark' has a wrong offset!");

}

