#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_EpicLinkageAccountInfo

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_EpicLinkageAccountInfo.PyWidget_EpicLinkageAccountInfo
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_EpicLinkageAccountInfo final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_EpicLinkageAccountInfo">();
	}
	static class UPyWidget_EpicLinkageAccountInfo* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_EpicLinkageAccountInfo>();
	}
};
static_assert(alignof(UPyWidget_EpicLinkageAccountInfo) == 0x000008, "Wrong alignment on UPyWidget_EpicLinkageAccountInfo");
static_assert(sizeof(UPyWidget_EpicLinkageAccountInfo) == 0x0005E8, "Wrong size on UPyWidget_EpicLinkageAccountInfo");

}

