#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Squad_ServerNode_Item

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Squad_ServerNode_Item.PyWidget_Squad_ServerNode_Item
// 0x0008 (0x05F0 - 0x05E8)
class UPyWidget_Squad_ServerNode_Item final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x6];                                      // 0x05E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPyDataAsset_Ping*                      PingInfoDataAsset;                                 // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Squad_ServerNode_Item">();
	}
	static class UPyWidget_Squad_ServerNode_Item* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Squad_ServerNode_Item>();
	}
};
static_assert(alignof(UPyWidget_Squad_ServerNode_Item) == 0x000008, "Wrong alignment on UPyWidget_Squad_ServerNode_Item");
static_assert(sizeof(UPyWidget_Squad_ServerNode_Item) == 0x0005F0, "Wrong size on UPyWidget_Squad_ServerNode_Item");
static_assert(offsetof(UPyWidget_Squad_ServerNode_Item, PingInfoDataAsset) == 0x0005E8, "Member 'UPyWidget_Squad_ServerNode_Item::PingInfoDataAsset' has a wrong offset!");

}

