#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Squad_WarmupGame_Card

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Squad_WarmupGame_Card.PyWidget_Squad_WarmupGame_Card
// 0x0028 (0x0610 - 0x05E8)
class UPyWidget_Squad_WarmupGame_Card final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x2];                                      // 0x05E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            HoverColor;                                        // 0x05E4(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            NormalColor;                                       // 0x05F8(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Squad_WarmupGame_Card">();
	}
	static class UPyWidget_Squad_WarmupGame_Card* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Squad_WarmupGame_Card>();
	}
};
static_assert(alignof(UPyWidget_Squad_WarmupGame_Card) == 0x000008, "Wrong alignment on UPyWidget_Squad_WarmupGame_Card");
static_assert(sizeof(UPyWidget_Squad_WarmupGame_Card) == 0x000610, "Wrong size on UPyWidget_Squad_WarmupGame_Card");
static_assert(offsetof(UPyWidget_Squad_WarmupGame_Card, HoverColor) == 0x0005E4, "Member 'UPyWidget_Squad_WarmupGame_Card::HoverColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Squad_WarmupGame_Card, NormalColor) == 0x0005F8, "Member 'UPyWidget_Squad_WarmupGame_Card::NormalColor' has a wrong offset!");

}

