#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Common_ProgressUnit

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_Common_ProgressUnit.PyWidget_Common_ProgressUnit
// 0x0030 (0x0618 - 0x05E8)
class UPyWidget_Common_ProgressUnit final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x2];                                      // 0x05E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           AttackerColor;                                     // 0x05E4(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           DefenderColor;                                     // 0x05F4(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_604[0x4];                                      // 0x0604(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                WBP_CompetitiveIdentifier;                         // 0x0608(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UWidgetAnimation*                       Anim_ProhibitProg;                                 // 0x0610(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void Construct();
	void Destruct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Common_ProgressUnit">();
	}
	static class UPyWidget_Common_ProgressUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Common_ProgressUnit>();
	}
};
static_assert(alignof(UPyWidget_Common_ProgressUnit) == 0x000008, "Wrong alignment on UPyWidget_Common_ProgressUnit");
static_assert(sizeof(UPyWidget_Common_ProgressUnit) == 0x000618, "Wrong size on UPyWidget_Common_ProgressUnit");
static_assert(offsetof(UPyWidget_Common_ProgressUnit, AttackerColor) == 0x0005E4, "Member 'UPyWidget_Common_ProgressUnit::AttackerColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressUnit, DefenderColor) == 0x0005F4, "Member 'UPyWidget_Common_ProgressUnit::DefenderColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressUnit, WBP_CompetitiveIdentifier) == 0x000608, "Member 'UPyWidget_Common_ProgressUnit::WBP_CompetitiveIdentifier' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressUnit, Anim_ProhibitProg) == 0x000610, "Member 'UPyWidget_Common_ProgressUnit::Anim_ProhibitProg' has a wrong offset!");

// PythonClass PyWidget_Common_ProgressUnit.PyWidget_Common_PayloadProgress
// 0x0020 (0x0608 - 0x05E8)
class UPyWidget_Common_PayloadProgress final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x2];                                      // 0x05E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           AttackerColor;                                     // 0x05E4(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           DefenderColor;                                     // 0x05F4(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Common_PayloadProgress">();
	}
	static class UPyWidget_Common_PayloadProgress* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Common_PayloadProgress>();
	}
};
static_assert(alignof(UPyWidget_Common_PayloadProgress) == 0x000008, "Wrong alignment on UPyWidget_Common_PayloadProgress");
static_assert(sizeof(UPyWidget_Common_PayloadProgress) == 0x000608, "Wrong size on UPyWidget_Common_PayloadProgress");
static_assert(offsetof(UPyWidget_Common_PayloadProgress, AttackerColor) == 0x0005E4, "Member 'UPyWidget_Common_PayloadProgress::AttackerColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_PayloadProgress, DefenderColor) == 0x0005F4, "Member 'UPyWidget_Common_PayloadProgress::DefenderColor' has a wrong offset!");

// PythonClass PyWidget_Common_ProgressUnit.PyWidget_Common_ProgressBarUnit
// 0x0078 (0x0660 - 0x05E8)
class UPyWidget_Common_ProgressBarUnit final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E2[0x2];                                      // 0x05E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         VisibleDistanceThreshHold;                         // 0x05E4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ApprochingMusicThreshHold;                         // 0x05E8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           Blue_FinishBgColor;                                // 0x05EC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           Red_FinishBgColor;                                 // 0x05FC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSlateColor                            TeamColorAlly;                                     // 0x060C(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            TeamColorEnemy;                                    // 0x0620(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            VXColorAlly;                                       // 0x0634(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            VXColorEnemy;                                      // 0x0648(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool bInVisible);
	void MarvelSetVisibleImmediately(bool bInVisible);
	void OnAnimationStarted(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Common_ProgressBarUnit">();
	}
	static class UPyWidget_Common_ProgressBarUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Common_ProgressBarUnit>();
	}
};
static_assert(alignof(UPyWidget_Common_ProgressBarUnit) == 0x000008, "Wrong alignment on UPyWidget_Common_ProgressBarUnit");
static_assert(sizeof(UPyWidget_Common_ProgressBarUnit) == 0x000660, "Wrong size on UPyWidget_Common_ProgressBarUnit");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, VisibleDistanceThreshHold) == 0x0005E4, "Member 'UPyWidget_Common_ProgressBarUnit::VisibleDistanceThreshHold' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, ApprochingMusicThreshHold) == 0x0005E8, "Member 'UPyWidget_Common_ProgressBarUnit::ApprochingMusicThreshHold' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, Blue_FinishBgColor) == 0x0005EC, "Member 'UPyWidget_Common_ProgressBarUnit::Blue_FinishBgColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, Red_FinishBgColor) == 0x0005FC, "Member 'UPyWidget_Common_ProgressBarUnit::Red_FinishBgColor' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, TeamColorAlly) == 0x00060C, "Member 'UPyWidget_Common_ProgressBarUnit::TeamColorAlly' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, TeamColorEnemy) == 0x000620, "Member 'UPyWidget_Common_ProgressBarUnit::TeamColorEnemy' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, VXColorAlly) == 0x000634, "Member 'UPyWidget_Common_ProgressBarUnit::VXColorAlly' has a wrong offset!");
static_assert(offsetof(UPyWidget_Common_ProgressBarUnit, VXColorEnemy) == 0x000648, "Member 'UPyWidget_Common_ProgressBarUnit::VXColorEnemy' has a wrong offset!");

}

