#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_SurrenderResult

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_SurrenderResult.PyWidget_SurrenderResult
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_SurrenderResult final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_SurrenderResult">();
	}
	static class UPyWidget_SurrenderResult* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_SurrenderResult>();
	}
};
static_assert(alignof(UPyWidget_SurrenderResult) == 0x000008, "Wrong alignment on UPyWidget_SurrenderResult");
static_assert(sizeof(UPyWidget_SurrenderResult) == 0x0005E8, "Wrong size on UPyWidget_SurrenderResult");

}

