#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_S1_2SeasonStory_MainPage1

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_S1_2SeasonStory_MainPage1.PyWidget_S1_2SeasonStory_MainPage1.Schedule_Left_Navigation
// 0x0010 (0x0010 - 0x0000)
struct PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation final
{
public:
	EUINavigation                                 Navigation_0;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation) == 0x000008, "Wrong alignment on PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation");
static_assert(sizeof(PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation) == 0x000010, "Wrong size on PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation");
static_assert(offsetof(PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation, Navigation_0) == 0x000000, "Member 'PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation::Navigation_0' has a wrong offset!");
static_assert(offsetof(PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation, ReturnValue) == 0x000008, "Member 'PyWidget_S1_2SeasonStory_MainPage1_Schedule_Left_Navigation::ReturnValue' has a wrong offset!");

}

