#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity116_DiscoveryFreeProps

#include "Basic.hpp"

#include "PyWidget_Button_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Activity116_DiscoveryFreeProps.PyWidget_Activity116_DiscoveryFreeProps
// 0x0000 (0x0748 - 0x0748)
class UPyWidget_Activity116_DiscoveryFreeProps final : public UPyWidget_Button
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Activity116_DiscoveryFreeProps">();
	}
	static class UPyWidget_Activity116_DiscoveryFreeProps* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Activity116_DiscoveryFreeProps>();
	}
};
static_assert(alignof(UPyWidget_Activity116_DiscoveryFreeProps) == 0x000008, "Wrong alignment on UPyWidget_Activity116_DiscoveryFreeProps");
static_assert(sizeof(UPyWidget_Activity116_DiscoveryFreeProps) == 0x000748, "Wrong size on UPyWidget_Activity116_DiscoveryFreeProps");

}

