#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_GalleryBook_DetailsPanel

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_GalleryBook_DetailsPanel.PyWidget_GalleryBook_DetailsPanel
// 0x0070 (0x0680 - 0x0610)
class UPyWidget_GalleryBook_DetailsPanel final : public UPyWidget_ModuleMainPanel
{
public:
	uint8                                         Pad_609[0x7];                                      // 0x0609(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UUserWidget>                SingleBookClass;                                   // 0x0610(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FGuideTipsStyle>                AppreciateGuideTips;                               // 0x0618(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<struct FGuideTipsStyle>                ViewMenuTipsStyle;                                 // 0x0628(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FGuideTipsStyle>                ScaleTipsStyle;                                    // 0x0638(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FGuideTipsStyle>                DragTipsStyle;                                     // 0x0648(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	class UTexture2D*                             AnimCoverTexture;                                  // 0x0658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UTexture2D*>                     AnimTextureList;                                   // 0x0660(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn, NativeAccessSpecifierPublic)
	class UTexture2D*                             AnimLeftTexture;                                   // 0x0670(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             AnimRightTexture;                                  // 0x0678(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void MarvelSetVisible(bool Visible);
	void OnVisibleChanged(bool bNewVisible);
	void Construct();
	void Destruct();
	void OnSoftTextureLoad(class UObject* Texture);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	struct FEventReply OnMouseWheel(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_GalleryBook_DetailsPanel">();
	}
	static class UPyWidget_GalleryBook_DetailsPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_GalleryBook_DetailsPanel>();
	}
};
static_assert(alignof(UPyWidget_GalleryBook_DetailsPanel) == 0x000008, "Wrong alignment on UPyWidget_GalleryBook_DetailsPanel");
static_assert(sizeof(UPyWidget_GalleryBook_DetailsPanel) == 0x000680, "Wrong size on UPyWidget_GalleryBook_DetailsPanel");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, SingleBookClass) == 0x000610, "Member 'UPyWidget_GalleryBook_DetailsPanel::SingleBookClass' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, AppreciateGuideTips) == 0x000618, "Member 'UPyWidget_GalleryBook_DetailsPanel::AppreciateGuideTips' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, ViewMenuTipsStyle) == 0x000628, "Member 'UPyWidget_GalleryBook_DetailsPanel::ViewMenuTipsStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, ScaleTipsStyle) == 0x000638, "Member 'UPyWidget_GalleryBook_DetailsPanel::ScaleTipsStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, DragTipsStyle) == 0x000648, "Member 'UPyWidget_GalleryBook_DetailsPanel::DragTipsStyle' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, AnimCoverTexture) == 0x000658, "Member 'UPyWidget_GalleryBook_DetailsPanel::AnimCoverTexture' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, AnimTextureList) == 0x000660, "Member 'UPyWidget_GalleryBook_DetailsPanel::AnimTextureList' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, AnimLeftTexture) == 0x000670, "Member 'UPyWidget_GalleryBook_DetailsPanel::AnimLeftTexture' has a wrong offset!");
static_assert(offsetof(UPyWidget_GalleryBook_DetailsPanel, AnimRightTexture) == 0x000678, "Member 'UPyWidget_GalleryBook_DetailsPanel::AnimRightTexture' has a wrong offset!");

}

