#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ReportTitleBP

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct ReportTitleBP.ReportTitleBP
// 0x0020 (0x0020 - 0x0000)
struct FReportTitleBP final
{
public:
	class FString                                 TitleName_5_A901CABD41CC79960A89EAB5B3056199;      // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Remark_11_BA2E7EB545B5F8A3F64C9ABBCD93865E;        // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(FReportTitleBP) == 0x000008, "Wrong alignment on FReportTitleBP");
static_assert(sizeof(FReportTitleBP) == 0x000020, "Wrong size on FReportTitleBP");
static_assert(offsetof(FReportTitleBP, TitleName_5_A901CABD41CC79960A89EAB5B3056199) == 0x000000, "Member 'FReportTitleBP::TitleName_5_A901CABD41CC79960A89EAB5B3056199' has a wrong offset!");
static_assert(offsetof(FReportTitleBP, Remark_11_BA2E7EB545B5F8A3F64C9ABBCD93865E) == 0x000010, "Member 'FReportTitleBP::Remark_11_BA2E7EB545B5F8A3F64C9ABBCD93865E' has a wrong offset!");

}

