#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RichTextChatIconViewImage_BP

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RichTextChatIconViewImage_BP.RichTextChatIconViewImage_BP_C
// 0x0000 (0x0038 - 0x0038)
class URichTextChatIconViewImage_BP_C final : public URichTextBlockImageDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RichTextChatIconViewImage_BP_C">();
	}
	static class URichTextChatIconViewImage_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URichTextChatIconViewImage_BP_C>();
	}
};
static_assert(alignof(URichTextChatIconViewImage_BP_C) == 0x000008, "Wrong alignment on URichTextChatIconViewImage_BP_C");
static_assert(sizeof(URichTextChatIconViewImage_BP_C) == 0x000038, "Wrong size on URichTextChatIconViewImage_BP_C");

}

