#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowAnim_LinkedAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct ShowAnim_LinkedAnimBP.ShowAnim_LinkedAnimBP_C.AnimBlueprintGeneratedMutableData
// 0x001F (0x0020 - 0x0001)
struct ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty;                                   // 0x0008(0x0010)(BlueprintVisible, EditFixedSize)
	float                                         __FloatProperty_0;                                 // 0x0018(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData) == 0x000008, "Wrong alignment on ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData) == 0x000020, "Wrong size on ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData, __ArrayProperty) == 0x000008, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData::__ArrayProperty' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_0) == 0x000018, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_0' has a wrong offset!");

// ScriptStruct ShowAnim_LinkedAnimBP.ShowAnim_LinkedAnimBP_C.AnimBlueprintGeneratedConstantData
// 0x0247 (0x0248 - 0x0001)
struct ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_588;                                // 0x0004(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_589;                                // 0x0010(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_590;                                // 0x001C(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_591;                                // 0x0028(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_592;                                // 0x0034(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_593;                                // 0x0040(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_594;                                // 0x004C(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_595;                                // 0x0058(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_596;                               // 0x0068(0x0010)(BlueprintVisible, EditFixedSize)
	class UBlendProfile*                          __BlendProfile_597;                                // 0x0078(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_598;                                  // 0x0080(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_599;                                // 0x0088(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_600;                                // 0x0089(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8A[0x6];                                       // 0x008A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_601;                               // 0x0090(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_602;                                // 0x00A0(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_603;                                // 0x00AC(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_604;                                // 0x00B8(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_605;                                 // 0x00C4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_606;                                // 0x00C8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_607;                                // 0x00CC(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_608;                                // 0x00D8(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_609;                                 // 0x00E4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_610;                                // 0x00E8(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_611;                                 // 0x00F4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_612;                                // 0x00F8(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_613;                                 // 0x0104(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_614;                                // 0x0108(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_615;                                // 0x0114(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_616;                               // 0x0120(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_617;                              // 0x0124(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_618;                               // 0x0150(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_619;                                // 0x0154(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_620;                                // 0x0155(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_621;                                // 0x0156(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_157[0x1];                                      // 0x0157(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_622;                                // 0x0158(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_623;                                 // 0x0164(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_624;                                // 0x0168(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_625;                                // 0x0174(0x000C)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_626;                                 // 0x0180(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNodeFunctionRef                   __StructProperty_627;                              // 0x0188(0x0028)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x01B0(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0230(0x0018)()
};
static_assert(alignof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData) == 0x000248, "Wrong size on ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_588) == 0x000004, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_588' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_589) == 0x000010, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_589' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_590) == 0x00001C, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_590' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_591) == 0x000028, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_591' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_592) == 0x000034, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_592' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_593) == 0x000040, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_593' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_594) == 0x00004C, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_594' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_595) == 0x000058, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_595' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_596) == 0x000068, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_596' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __BlendProfile_597) == 0x000078, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__BlendProfile_597' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __CurveFloat_598) == 0x000080, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__CurveFloat_598' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_599) == 0x000088, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_599' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_600) == 0x000089, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_600' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_601) == 0x000090, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_601' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_602) == 0x0000A0, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_602' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_603) == 0x0000AC, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_603' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_604) == 0x0000B8, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_604' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_605) == 0x0000C4, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_605' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __BoolProperty_606) == 0x0000C8, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__BoolProperty_606' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_607) == 0x0000CC, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_607' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_608) == 0x0000D8, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_608' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_609) == 0x0000E4, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_609' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_610) == 0x0000E8, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_610' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_611) == 0x0000F4, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_611' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_612) == 0x0000F8, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_612' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_613) == 0x000104, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_613' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_614) == 0x000108, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_614' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_615) == 0x000114, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_615' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __FloatProperty_616) == 0x000120, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__FloatProperty_616' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __StructProperty_617) == 0x000124, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__StructProperty_617' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __FloatProperty_618) == 0x000150, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__FloatProperty_618' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __BoolProperty_619) == 0x000154, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__BoolProperty_619' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_620) == 0x000155, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_620' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __ByteProperty_621) == 0x000156, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__ByteProperty_621' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_622) == 0x000158, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_622' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_623) == 0x000164, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_623' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_624) == 0x000168, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_624' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_625) == 0x000174, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_625' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_626) == 0x000180, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_626' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, __StructProperty_627) == 0x000188, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::__StructProperty_627' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x0001B0, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000230, "Member 'ShowAnim_LinkedAnimBP::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

}

