#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Summoned_10234101_BP

#include "Basic.hpp"

#include "Hero_1023_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Summoned_10234101_BP.Summoned_10234101_BP_C
// 0x0020 (0x0AE0 - 0x0AC0)
class ASummoned_10234101_BP_C final : public ASummoned_10234101
{
public:
	class USummonedModifierComponent*             SummonedModifier;                                  // 0x0AC0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNavEffectBoxComponent*                 NavEffectBox;                                      // 0x0AC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMarvelNavModifierComponent*            MarvelNavModifier;                                 // 0x0AD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Summoned_10234101_BP_C">();
	}
	static class ASummoned_10234101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10234101_BP_C>();
	}
};
static_assert(alignof(ASummoned_10234101_BP_C) == 0x000010, "Wrong alignment on ASummoned_10234101_BP_C");
static_assert(sizeof(ASummoned_10234101_BP_C) == 0x000AE0, "Wrong size on ASummoned_10234101_BP_C");
static_assert(offsetof(ASummoned_10234101_BP_C, SummonedModifier) == 0x000AC0, "Member 'ASummoned_10234101_BP_C::SummonedModifier' has a wrong offset!");
static_assert(offsetof(ASummoned_10234101_BP_C, NavEffectBox) == 0x000AC8, "Member 'ASummoned_10234101_BP_C::NavEffectBox' has a wrong offset!");
static_assert(offsetof(ASummoned_10234101_BP_C, MarvelNavModifier) == 0x000AD0, "Member 'ASummoned_10234101_BP_C::MarvelNavModifier' has a wrong offset!");

}

