#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Setting_ExtraSensCurve

#include "Basic.hpp"

#include "PyWidget_AimCurve_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Setting_ExtraSensCurve.WBP_Setting_ExtraSensCurve_C
// 0x0008 (0x05F8 - 0x05F0)
class UWBP_Setting_ExtraSensCurve_C final : public UPyWidget_DeadZoneExtraSensiCurve
{
public:
	class UWBP_Setting_ExtraSensCurve_Panel_C*    WBP_Setting_ExtraSensCurve_Panel;                  // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Setting_ExtraSensCurve_C">();
	}
	static class UWBP_Setting_ExtraSensCurve_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Setting_ExtraSensCurve_C>();
	}
};
static_assert(alignof(UWBP_Setting_ExtraSensCurve_C) == 0x000008, "Wrong alignment on UWBP_Setting_ExtraSensCurve_C");
static_assert(sizeof(UWBP_Setting_ExtraSensCurve_C) == 0x0005F8, "Wrong size on UWBP_Setting_ExtraSensCurve_C");
static_assert(offsetof(UWBP_Setting_ExtraSensCurve_C, WBP_Setting_ExtraSensCurve_Panel) == 0x0005F0, "Member 'UWBP_Setting_ExtraSensCurve_C::WBP_Setting_ExtraSensCurve_Panel' has a wrong offset!");

}

