#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GuidePanel

#include "Basic.hpp"

#include "PyWidget_GuidePanel_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_GuidePanel.WBP_GuidePanel_C
// 0x0038 (0x0890 - 0x0858)
class UWBP_GuidePanel_C final : public UPyWidget_GuidePanel
{
public:
	class UMarvelHorizontalBox*                   HBox_1;                                            // 0x0858(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage;                                       // 0x0860(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage_1;                                     // 0x0868(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage_2;                                     // 0x0870(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage_52;                                    // 0x0878(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox;                                           // 0x0880(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_1;                                         // 0x0888(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_GuidePanel_C">();
	}
	static class UWBP_GuidePanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GuidePanel_C>();
	}
};
static_assert(alignof(UWBP_GuidePanel_C) == 0x000008, "Wrong alignment on UWBP_GuidePanel_C");
static_assert(sizeof(UWBP_GuidePanel_C) == 0x000890, "Wrong size on UWBP_GuidePanel_C");
static_assert(offsetof(UWBP_GuidePanel_C, HBox_1) == 0x000858, "Member 'UWBP_GuidePanel_C::HBox_1' has a wrong offset!");
static_assert(offsetof(UWBP_GuidePanel_C, MarvelImage) == 0x000860, "Member 'UWBP_GuidePanel_C::MarvelImage' has a wrong offset!");
static_assert(offsetof(UWBP_GuidePanel_C, MarvelImage_1) == 0x000868, "Member 'UWBP_GuidePanel_C::MarvelImage_1' has a wrong offset!");
static_assert(offsetof(UWBP_GuidePanel_C, MarvelImage_2) == 0x000870, "Member 'UWBP_GuidePanel_C::MarvelImage_2' has a wrong offset!");
static_assert(offsetof(UWBP_GuidePanel_C, MarvelImage_52) == 0x000878, "Member 'UWBP_GuidePanel_C::MarvelImage_52' has a wrong offset!");
static_assert(offsetof(UWBP_GuidePanel_C, SizeBox) == 0x000880, "Member 'UWBP_GuidePanel_C::SizeBox' has a wrong offset!");
static_assert(offsetof(UWBP_GuidePanel_C, SizeBox_1) == 0x000888, "Member 'UWBP_GuidePanel_C::SizeBox_1' has a wrong offset!");

}

