#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Common_NameTips

#include "Basic.hpp"

#include "PyWidget_Common_NameTips_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Common_NameTips.WBP_Common_NameTips_C
// 0x0028 (0x0788 - 0x0760)
class UWBP_Common_NameTips_C final : public UPyWidget_Common_NameTips
{
public:
	class UMarvelImage*                           Img_Bg;                                            // 0x0760(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Frame;                                         // 0x0768(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Icon;                                      // 0x0770(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelRichTextBlock*                   Text_Name;                                         // 0x0778(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Common_KeyWidget_C*                WBP_Common_KeyWidget;                              // 0x0780(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Common_NameTips_C">();
	}
	static class UWBP_Common_NameTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Common_NameTips_C>();
	}
};
static_assert(alignof(UWBP_Common_NameTips_C) == 0x000008, "Wrong alignment on UWBP_Common_NameTips_C");
static_assert(sizeof(UWBP_Common_NameTips_C) == 0x000788, "Wrong size on UWBP_Common_NameTips_C");
static_assert(offsetof(UWBP_Common_NameTips_C, Img_Bg) == 0x000760, "Member 'UWBP_Common_NameTips_C::Img_Bg' has a wrong offset!");
static_assert(offsetof(UWBP_Common_NameTips_C, Img_Frame) == 0x000768, "Member 'UWBP_Common_NameTips_C::Img_Frame' has a wrong offset!");
static_assert(offsetof(UWBP_Common_NameTips_C, Overlay_Icon) == 0x000770, "Member 'UWBP_Common_NameTips_C::Overlay_Icon' has a wrong offset!");
static_assert(offsetof(UWBP_Common_NameTips_C, Text_Name) == 0x000778, "Member 'UWBP_Common_NameTips_C::Text_Name' has a wrong offset!");
static_assert(offsetof(UWBP_Common_NameTips_C, WBP_Common_KeyWidget) == 0x000780, "Member 'UWBP_Common_NameTips_C::WBP_Common_KeyWidget' has a wrong offset!");

}

